begin
  execute immediate q'<
CREATE SEQUENCE "ADMIN"."GITHUB_INSTALLED_PROJECTS_SEQ" START WITH 1 NOCACHE ORDER
>';

  execute immediate q'<
CREATE TABLE "ADMIN"."GITHUB_INSTALLED_PROJECTS" (
    "ID"             NUMBER DEFAULT ON NULL "ADMIN"."GITHUB_INSTALLED_PROJECTS_SEQ".nextval
        CONSTRAINT "NNC_GITHUB_INSTALLED_PROJECTS_GITHUB_INSTALLED_PROJECTS_ID" NOT NULL,
    "GITHUB_REPO"    VARCHAR2(256)
        CONSTRAINT "NNC_GITHUB_INSTALLED_PROJECTS_GITHUB_REPO" NOT NULL,
    "DIRECTORY_NAME" VARCHAR2(4000 BYTE)
        CONSTRAINT "NNC_GITHUB_INSTALLED_PROJECTS_DIRECTORY_NAME" NOT NULL,
    "OWNER"          VARCHAR2(128)
        CONSTRAINT "NNC_GITHUB_INSTALLED_PROJECTS_OWNER" NOT NULL
)
LOGGING
>';

  execute immediate q'<
COMMENT ON TABLE "ADMIN"."GITHUB_INSTALLED_PROJECTS" IS
    'GitHub installed projects.'
>';

  execute immediate q'<
ALTER TABLE "ADMIN"."GITHUB_INSTALLED_PROJECTS" ADD CONSTRAINT "GITHUB_INSTALLED_PROJECTS_PK" PRIMARY KEY ( "ID" )
>';

  execute immediate q'<
ALTER TABLE "ADMIN"."GITHUB_INSTALLED_PROJECTS" ADD CONSTRAINT "GITHUB_INSTALLED_PROJECTS_UK" UNIQUE ( "GITHUB_REPO",
                                                                                                       "DIRECTORY_NAME" )
>';
exception
  when others
  then
    -- ORA-00955: name is already used by an existing object
    if sqlcode in (-955) then null; else raise; end if;
end;
/
