declare
begin
  execute immediate q'<
CREATE SEQUENCE "ADMIN"."GITHUB_INSTALLED_VERSIONS_SEQ" START WITH 1 NOCACHE ORDER
>';

  execute immediate q'<
CREATE TABLE "ADMIN"."GITHUB_INSTALLED_VERSIONS" (
    "ID"                           INTEGER DEFAULT ON NULL "ADMIN"."GITHUB_INSTALLED_VERSIONS_SEQ".nextval
        CONSTRAINT "NNC_GITHUB_INSTALLED_VERSIONS_ID" NOT NULL,
    "GITHUB_INSTALLED_PROJECTS_ID" NUMBER
        CONSTRAINT "NNC_GITHUB_INSTALLED_VERSIONS_PROJECT_ID" NOT NULL,
    "BASE_NAME"                    VARCHAR2(4000 BYTE)
        CONSTRAINT "NNC_GITHUB_INSTALLED_VERSIONS_BASE_NAME" NOT NULL,
    "DATE_CREATED"                 DATE
        CONSTRAINT "NNC_GITHUB_INSTALLED_VERSIONS_DATE_CREATED" NOT NULL,
    "CHECKSUM"                     VARCHAR2(128)
        CONSTRAINT "NNC_GITHUB_INSTALLED_VERSIONS_CHECKSUM" NOT NULL,
    "BYTES"                        INTEGER
        CONSTRAINT "NNC_GITHUB_INSTALLED_VERSIONS_BYTES" NOT NULL,
    "SUCCESS"                      NUMBER(1)
        CONSTRAINT "NNC_GITHUB_INSTALLED_VERSIONS_SUCCESS" NOT NULL
)
>';

  execute immediate q'<
ALTER TABLE "ADMIN"."GITHUB_INSTALLED_VERSIONS" ADD CONSTRAINT "CK_GITHUB_INSTALLED_VERSIONS_BYTES" CHECK ( "BYTES" >= 0 )
>';

  execute immediate q'<
ALTER TABLE "ADMIN"."GITHUB_INSTALLED_VERSIONS"
    ADD CONSTRAINT "CK_GITHUB_INSTALLED_VERSIONS_SUCCESS" CHECK ( "SUCCESS" IN ( 0, 1 ) )
>';

  execute immediate q'<
COMMENT ON TABLE "ADMIN"."GITHUB_INSTALLED_VERSIONS" IS
    'GitHub installation history.'
>';

  execute immediate q'<
ALTER TABLE "ADMIN"."GITHUB_INSTALLED_VERSIONS" ADD CONSTRAINT "GITHUB_INSTALLED_VERSIONS_PK" PRIMARY KEY ( "ID" )
>';

  execute immediate q'<
ALTER TABLE "ADMIN"."GITHUB_INSTALLED_VERSIONS"
    ADD CONSTRAINT "GITHUB_INSTALLED_VERSIONS_UK" UNIQUE ( "GITHUB_INSTALLED_PROJECTS_ID",
                                                           "BASE_NAME",
                                                           "DATE_CREATED" )
>';
                                                           
  execute immediate q'<
ALTER TABLE "ADMIN"."GITHUB_INSTALLED_VERSIONS"
    ADD CONSTRAINT "GITHUB_INSTALLED_PROJECTS_FK" FOREIGN KEY ( "GITHUB_INSTALLED_PROJECTS_ID" )
        REFERENCES "ADMIN"."GITHUB_INSTALLED_PROJECTS" ( "ID" )
    NOT DEFERRABLE
>';

  execute immediate q'<
CREATE TRIGGER "ADMIN"."FKNTM_GITHUB_INSTALLED_VERSIONS" BEFORE
    UPDATE OF "GITHUB_INSTALLED_PROJECTS_ID" ON "ADMIN"."GITHUB_INSTALLED_VERSIONS"
BEGIN
    raise_application_error(-20225, 'Non Transferable FK constraint  on table "ADMIN"."GITHUB_INSTALLED_VERSIONS" is violated');
END;
>';

exception
  when others
  then
    -- ORA-00955: name is already used by an existing object
    if sqlcode in (-955) then null; else raise; end if;
end;
/
