CREATE TYPE "ORACLE_TOOLS"."T_OBJECT_INFO_REC" AS OBJECT
(OBJECT_SCHEMA VARCHAR2(128 CHAR),
OBJECT_TYPE VARCHAR2(30 CHAR),
OBJECT_NAME VARCHAR2(4000 CHAR),
BASE_OBJECT_SCHEMA VARCHAR2(128 CHAR),
BASE_OBJECT_TYPE VARCHAR2(30 CHAR),
BASE_OBJECT_NAME VARCHAR2(4000 CHAR),
COLUMN_NAME VARCHAR2(128 CHAR),
GRANTEE VARCHAR2(128 CHAR),
PRIVILEGE VARCHAR2(40 CHAR),
GRANTABLE VARCHAR2(3 CHAR));
/

