-- CREATE TYPE should not use CREATE TYPE .. AS TABLE OF "SCHEMA"."OBJECT"
-- otherwise the unit test for synchronize will fail
-- since schema EMPTY can not grant those table types when they are base on ORACLE_TOOLS objects.

/* To help Flyway */
BEGIN
  EXECUTE IMMEDIATE q'[
CREATE TYPE "ORACLE_TOOLS"."T_DDL_INFO_REC" AS OBJECT
(VERB VARCHAR2(4000 CHAR),
OBJECT_SCHEMA VARCHAR2(128 CHAR),
OBJECT_TYPE VARCHAR2(30 CHAR),
OBJECT_NAME VARCHAR2(4000 CHAR),
BASE_OBJECT_SCHEMA VARCHAR2(128 CHAR),
BASE_OBJECT_TYPE VARCHAR2(30 CHAR),
BASE_OBJECT_NAME VARCHAR2(4000 CHAR),
COLUMN_NAME VARCHAR2(128 CHAR),
GRANTEE VARCHAR2(128 CHAR),
PRIVILEGE VARCHAR2(40 CHAR),
GRANTABLE VARCHAR2(3 CHAR),
DDL# INTEGER,
TEXT "T_TEXT_TAB")
]';
END;
/
