/* To help Flyway */
BEGIN
  EXECUTE IMMEDIATE q'[
CREATE TYPE "ORACLE_TOOLS"."T_SORT_OBJECTS_BY_DEPS_REC" AS OBJECT (OBJECT_SCHEMA VARCHAR2(128 CHAR),
OBJECT_TYPE VARCHAR2(30 CHAR),
OBJECT_NAME VARCHAR2(4000 CHAR),
DEPENDENCY_LIST VARCHAR2(4000 CHAR),
NR INTEGER)
]';
END;
/
