REMARK Try to call Flyway script beforeEachMigrate.sql (add its directory to SQLPATH) so that PLSQL_CCFlags can be set.
REMARK But no harm done if it is not there.

whenever oserror continue
whenever sqlerror continue
@@beforeEachMigrate.sql

whenever oserror exit failure
whenever sqlerror exit failure
set define off sqlblanklines on
ALTER SESSION SET PLSQL_WARNINGS = 'ENABLE:ALL';

prompt @@01.SEQUENCE.WEB_SERVICE_REQUEST_SEQ.sql
@@01.SEQUENCE.WEB_SERVICE_REQUEST_SEQ.sql
prompt @@02.TYPE_SPEC.REST_WEB_SERVICE_DELETE_REQUEST_TYP.sql
@@02.TYPE_SPEC.REST_WEB_SERVICE_DELETE_REQUEST_TYP.sql
show errors TYPE "REST_WEB_SERVICE_DELETE_REQUEST_TYP"
prompt @@02.TYPE_SPEC.REST_WEB_SERVICE_GET_REQUEST_TYP.sql
@@02.TYPE_SPEC.REST_WEB_SERVICE_GET_REQUEST_TYP.sql
show errors TYPE "REST_WEB_SERVICE_GET_REQUEST_TYP"
prompt @@02.TYPE_SPEC.REST_WEB_SERVICE_PATCH_REQUEST_TYP.sql
@@02.TYPE_SPEC.REST_WEB_SERVICE_PATCH_REQUEST_TYP.sql
show errors TYPE "REST_WEB_SERVICE_PATCH_REQUEST_TYP"
prompt @@02.TYPE_SPEC.REST_WEB_SERVICE_POST_REQUEST_TYP.sql
@@02.TYPE_SPEC.REST_WEB_SERVICE_POST_REQUEST_TYP.sql
show errors TYPE "REST_WEB_SERVICE_POST_REQUEST_TYP"
prompt @@02.TYPE_SPEC.REST_WEB_SERVICE_PUT_REQUEST_TYP.sql
@@02.TYPE_SPEC.REST_WEB_SERVICE_PUT_REQUEST_TYP.sql
show errors TYPE "REST_WEB_SERVICE_PUT_REQUEST_TYP"
prompt @@02.TYPE_SPEC.REST_WEB_SERVICE_REQUEST_TYP.sql
@@02.TYPE_SPEC.REST_WEB_SERVICE_REQUEST_TYP.sql
show errors TYPE "REST_WEB_SERVICE_REQUEST_TYP"
prompt @@02.TYPE_SPEC.HTTP_REQUEST_RESPONSE_TYP.sql
@@02.TYPE_SPEC.HTTP_REQUEST_RESPONSE_TYP.sql
show errors TYPE "HTTP_REQUEST_RESPONSE_TYP"
prompt @@02.TYPE_SPEC.WEB_SERVICE_REQUEST_TYP.sql
@@02.TYPE_SPEC.WEB_SERVICE_REQUEST_TYP.sql
show errors TYPE "WEB_SERVICE_REQUEST_TYP"
prompt @@02.TYPE_SPEC.WEB_SERVICE_RESPONSE_TYP.sql
@@02.TYPE_SPEC.WEB_SERVICE_RESPONSE_TYP.sql
show errors TYPE "WEB_SERVICE_RESPONSE_TYP"
prompt @@02.TYPE_SPEC.HTTP_COOKIE_TAB_TYP.sql
@@02.TYPE_SPEC.HTTP_COOKIE_TAB_TYP.sql
show errors TYPE "HTTP_COOKIE_TAB_TYP"
prompt @@02.TYPE_SPEC.PROPERTY_TAB_TYP.sql
@@02.TYPE_SPEC.PROPERTY_TAB_TYP.sql
show errors TYPE "PROPERTY_TAB_TYP"
prompt @@02.TYPE_SPEC.HTTP_COOKIE_TYP.sql
@@02.TYPE_SPEC.HTTP_COOKIE_TYP.sql
show errors TYPE "HTTP_COOKIE_TYP"
prompt @@02.TYPE_SPEC.MSG_TYP.sql
@@02.TYPE_SPEC.MSG_TYP.sql
show errors TYPE "MSG_TYP"
prompt @@02.TYPE_SPEC.PROPERTY_TYP.sql
@@02.TYPE_SPEC.PROPERTY_TYP.sql
show errors TYPE "PROPERTY_TYP"
prompt @@R__09.PACKAGE_SPEC.WEB_SERVICE_PKG.sql
@@R__09.PACKAGE_SPEC.WEB_SERVICE_PKG.sql
show errors PACKAGE "WEB_SERVICE_PKG"
prompt @@R__09.PACKAGE_SPEC.MSG_SCHEDULER_PKG.sql
@@R__09.PACKAGE_SPEC.MSG_SCHEDULER_PKG.sql
show errors PACKAGE "MSG_SCHEDULER_PKG"
prompt @@R__09.PACKAGE_SPEC.HTTP_REQUEST_RESPONSE_PKG.sql
@@R__09.PACKAGE_SPEC.HTTP_REQUEST_RESPONSE_PKG.sql
show errors PACKAGE "HTTP_REQUEST_RESPONSE_PKG"
prompt @@R__09.PACKAGE_SPEC.MSG_AQ_PKG.sql
@@R__09.PACKAGE_SPEC.MSG_AQ_PKG.sql
show errors PACKAGE "MSG_AQ_PKG"
prompt @@R__09.PACKAGE_SPEC.MSG_PKG.sql
@@R__09.PACKAGE_SPEC.MSG_PKG.sql
show errors PACKAGE "MSG_PKG"
prompt @@R__10.VIEW.MSG_QUEUE_INFO_V.sql
@@R__10.VIEW.MSG_QUEUE_INFO_V.sql
show errors VIEW "MSG_QUEUE_INFO_V"
prompt @@R__11.PROCEDURE.MSG_NOTIFICATION_PRC.sql
@@R__11.PROCEDURE.MSG_NOTIFICATION_PRC.sql
show errors PROCEDURE "MSG_NOTIFICATION_PRC"
prompt @@R__14.PACKAGE_BODY.WEB_SERVICE_PKG.sql
@@R__14.PACKAGE_BODY.WEB_SERVICE_PKG.sql
show errors PACKAGE BODY "WEB_SERVICE_PKG"
prompt @@R__14.PACKAGE_BODY.MSG_SCHEDULER_PKG.sql
@@R__14.PACKAGE_BODY.MSG_SCHEDULER_PKG.sql
show errors PACKAGE BODY "MSG_SCHEDULER_PKG"
prompt @@R__14.PACKAGE_BODY.HTTP_REQUEST_RESPONSE_PKG.sql
@@R__14.PACKAGE_BODY.HTTP_REQUEST_RESPONSE_PKG.sql
show errors PACKAGE BODY "HTTP_REQUEST_RESPONSE_PKG"
prompt @@R__14.PACKAGE_BODY.MSG_AQ_PKG.sql
@@R__14.PACKAGE_BODY.MSG_AQ_PKG.sql
show errors PACKAGE BODY "MSG_AQ_PKG"
prompt @@R__14.PACKAGE_BODY.MSG_PKG.sql
@@R__14.PACKAGE_BODY.MSG_PKG.sql
show errors PACKAGE BODY "MSG_PKG"
prompt @@R__15.TYPE_BODY.REST_WEB_SERVICE_REQUEST_TYP.sql
@@R__15.TYPE_BODY.REST_WEB_SERVICE_REQUEST_TYP.sql
show errors TYPE BODY "REST_WEB_SERVICE_REQUEST_TYP"
prompt @@R__15.TYPE_BODY.WEB_SERVICE_RESPONSE_TYP.sql
@@R__15.TYPE_BODY.WEB_SERVICE_RESPONSE_TYP.sql
show errors TYPE BODY "WEB_SERVICE_RESPONSE_TYP"
prompt @@R__15.TYPE_BODY.HTTP_REQUEST_RESPONSE_TYP.sql
@@R__15.TYPE_BODY.HTTP_REQUEST_RESPONSE_TYP.sql
show errors TYPE BODY "HTTP_REQUEST_RESPONSE_TYP"
prompt @@R__15.TYPE_BODY.WEB_SERVICE_REQUEST_TYP.sql
@@R__15.TYPE_BODY.WEB_SERVICE_REQUEST_TYP.sql
show errors TYPE BODY "WEB_SERVICE_REQUEST_TYP"
prompt @@R__15.TYPE_BODY.MSG_TYP.sql
@@R__15.TYPE_BODY.MSG_TYP.sql
show errors TYPE BODY "MSG_TYP"
prompt @@R__15.TYPE_BODY.REST_WEB_SERVICE_GET_REQUEST_TYP.sql
@@R__15.TYPE_BODY.REST_WEB_SERVICE_GET_REQUEST_TYP.sql
show errors TYPE BODY "REST_WEB_SERVICE_GET_REQUEST_TYP"
prompt @@R__15.TYPE_BODY.REST_WEB_SERVICE_DELETE_REQUEST_TYP.sql
@@R__15.TYPE_BODY.REST_WEB_SERVICE_DELETE_REQUEST_TYP.sql
show errors TYPE BODY "REST_WEB_SERVICE_DELETE_REQUEST_TYP"
prompt @@R__15.TYPE_BODY.REST_WEB_SERVICE_PATCH_REQUEST_TYP.sql
@@R__15.TYPE_BODY.REST_WEB_SERVICE_PATCH_REQUEST_TYP.sql
show errors TYPE BODY "REST_WEB_SERVICE_PATCH_REQUEST_TYP"
prompt @@R__15.TYPE_BODY.REST_WEB_SERVICE_POST_REQUEST_TYP.sql
@@R__15.TYPE_BODY.REST_WEB_SERVICE_POST_REQUEST_TYP.sql
show errors TYPE BODY "REST_WEB_SERVICE_POST_REQUEST_TYP"
prompt @@R__15.TYPE_BODY.REST_WEB_SERVICE_PUT_REQUEST_TYP.sql
@@R__15.TYPE_BODY.REST_WEB_SERVICE_PUT_REQUEST_TYP.sql
show errors TYPE BODY "REST_WEB_SERVICE_PUT_REQUEST_TYP"
