whenever sqlerror exit failure
whenever oserror exit failure

prompt @../full/R__15.TYPE_BODY.MSG_TYP.sql
@../full/R__15.TYPE_BODY.MSG_TYP.sql
prompt @../full/R__15.TYPE_BODY.HTTP_REQUEST_RESPONSE_TYP.sql
@../full/R__15.TYPE_BODY.HTTP_REQUEST_RESPONSE_TYP.sql
prompt @../full/R__15.TYPE_BODY.WEB_SERVICE_REQUEST_TYP.sql
@../full/R__15.TYPE_BODY.WEB_SERVICE_REQUEST_TYP.sql
prompt @../full/R__15.TYPE_BODY.WEB_SERVICE_RESPONSE_TYP.sql
@../full/R__15.TYPE_BODY.WEB_SERVICE_RESPONSE_TYP.sql
prompt @../full/R__15.TYPE_BODY.REST_WEB_SERVICE_REQUEST_TYP.sql
@../full/R__15.TYPE_BODY.REST_WEB_SERVICE_REQUEST_TYP.sql
prompt @../full/R__15.TYPE_BODY.REST_WEB_SERVICE_GET_REQUEST_TYP.sql
@../full/R__15.TYPE_BODY.REST_WEB_SERVICE_GET_REQUEST_TYP.sql
prompt @../full/R__15.TYPE_BODY.REST_WEB_SERVICE_POST_REQUEST_TYP.sql
@../full/R__15.TYPE_BODY.REST_WEB_SERVICE_POST_REQUEST_TYP.sql
prompt @../full/R__15.TYPE_BODY.REST_WEB_SERVICE_PATCH_REQUEST_TYP.sql
@../full/R__15.TYPE_BODY.REST_WEB_SERVICE_PATCH_REQUEST_TYP.sql
prompt @../full/R__15.TYPE_BODY.REST_WEB_SERVICE_DELETE_REQUEST_TYP.sql
@../full/R__15.TYPE_BODY.REST_WEB_SERVICE_DELETE_REQUEST_TYP.sql
prompt @../full/R__15.TYPE_BODY.REST_WEB_SERVICE_PUT_REQUEST_TYP.sql
@../full/R__15.TYPE_BODY.REST_WEB_SERVICE_PUT_REQUEST_TYP.sql
