// -*- mode: groovy; coding: utf-8 -*-
pipeline {
    agent any
    options {
        skipDefaultCheckout()
    }
    stages {
        stage("pipeline") {
            steps {
                script {
                    pipelineConfig.application_environments.each{ env ->
                        println "environment: ${env}"
                        process env.getValue()
                    }
                }
            }
        }
    }
    post {
        // Clean after build
        always {
            cleanWs(cleanWhenNotBuilt: false,
                    deleteDirs: true,
                    disableDeferredWipeout: true,
                    notFailBuild: true,
                    patterns: [[pattern: '.gitignore', type: 'INCLUDE'],
                               [pattern: '.propsfile', type: 'EXCLUDE']])
        }
    }
}
