// -*- mode: groovy; coding: utf-8 -*-
pipeline {
		agent any
    options {
        skipDefaultCheckout()
    }
    tools {
        maven pipelineConfig.maven
        jdk pipelineConfig.jdk
    }
    stages {
        stage("dev") {
            steps {
                process dev
            }
        }
        stage("test") {
            steps {
                process test
            }
        }
    }
    post {
        // Clean after build
        always {
            cleanWs(cleanWhenNotBuilt: false,
                    deleteDirs: true,
                    disableDeferredWipeout: true,
                    notFailBuild: true,
                    patterns: [[pattern: '.gitignore', type: 'INCLUDE'],
                               [pattern: '.propsfile', type: 'EXCLUDE']])
        }
    }
}
