whenever oserror exit failure
whenever sqlerror exit failure
set define off sqlblanklines on
ALTER SESSION SET PLSQL_WARNINGS = 'ENABLE:ALL';

prompt @@R__09.PACKAGE_SPEC.UI_APEX_MESSAGES_PKG.sql
@@R__09.PACKAGE_SPEC.UI_APEX_MESSAGES_PKG.sql
prompt @@R__09.PACKAGE_SPEC.UI_ERROR_PKG.sql
@@R__09.PACKAGE_SPEC.UI_ERROR_PKG.sql
prompt @@R__09.PACKAGE_SPEC.UI_SESSION_PKG.sql
@@R__09.PACKAGE_SPEC.UI_SESSION_PKG.sql
prompt @@R__09.PACKAGE_SPEC.UI_USER_MANAGEMENT_PKG.sql
@@R__09.PACKAGE_SPEC.UI_USER_MANAGEMENT_PKG.sql
prompt @@R__10.VIEW.UI_APEX_MESSAGES_V.sql
@@R__10.VIEW.UI_APEX_MESSAGES_V.sql
prompt @@R__14.PACKAGE_BODY.UI_APEX_MESSAGES_PKG.sql
@@R__14.PACKAGE_BODY.UI_APEX_MESSAGES_PKG.sql
prompt @@R__14.PACKAGE_BODY.UI_ERROR_PKG.sql
@@R__14.PACKAGE_BODY.UI_ERROR_PKG.sql
prompt @@R__14.PACKAGE_BODY.UI_SESSION_PKG.sql
@@R__14.PACKAGE_BODY.UI_SESSION_PKG.sql
prompt @@R__14.PACKAGE_BODY.UI_USER_MANAGEMENT_PKG.sql
@@R__14.PACKAGE_BODY.UI_USER_MANAGEMENT_PKG.sql
prompt @@R__10.VIEW.UI_APEX_MESSAGES_V.sql
@@R__10.VIEW.UI_APEX_MESSAGES_V.sql
prompt @@30.PROCOBJ.UI_RESET_PWD_JOB.sql
@@30.PROCOBJ.UI_RESET_PWD_JOB.sql
