REMARK Try to call Flyway script beforeEachMigrate.sql (add its directory to SQLPATH) so that PLSQL_CCFlags can be set.
REMARK But no harm done if it is not there.

whenever oserror continue
whenever sqlerror continue
@@beforeEachMigrate.sql

whenever oserror exit failure
whenever sqlerror exit failure
set define off sqlblanklines on
ALTER SESSION SET PLSQL_WARNINGS = 'ENABLE:ALL';

prompt @@R__09.PACKAGE_SPEC.UI_APEX_MESSAGES_PKG.sql
@@R__09.PACKAGE_SPEC.UI_APEX_MESSAGES_PKG.sql
show errors PACKAGE "UI_APEX_MESSAGES_PKG"
prompt @@R__09.PACKAGE_SPEC.UI_SESSION_PKG.sql
@@R__09.PACKAGE_SPEC.UI_SESSION_PKG.sql
show errors PACKAGE "UI_SESSION_PKG"
prompt @@R__09.PACKAGE_SPEC.UI_APEX_SYNCHRONIZE.sql
@@R__09.PACKAGE_SPEC.UI_APEX_SYNCHRONIZE.sql
show errors PACKAGE "UI_APEX_SYNCHRONIZE"
prompt @@R__09.PACKAGE_SPEC.UI_ERROR_PKG.sql
@@R__09.PACKAGE_SPEC.UI_ERROR_PKG.sql
show errors PACKAGE "UI_ERROR_PKG"
prompt @@R__09.PACKAGE_SPEC.UI_USER_MANAGEMENT_PKG.sql
@@R__09.PACKAGE_SPEC.UI_USER_MANAGEMENT_PKG.sql
show errors PACKAGE "UI_USER_MANAGEMENT_PKG"
prompt @@R__10.VIEW.UI_APEX_MESSAGES_V.sql
@@R__10.VIEW.UI_APEX_MESSAGES_V.sql
show errors VIEW "UI_APEX_MESSAGES_V"
prompt @@R__14.PACKAGE_BODY.UI_APEX_MESSAGES_PKG.sql
@@R__14.PACKAGE_BODY.UI_APEX_MESSAGES_PKG.sql
show errors PACKAGE BODY "UI_APEX_MESSAGES_PKG"
prompt @@R__14.PACKAGE_BODY.UI_APEX_SYNCHRONIZE.sql
@@R__14.PACKAGE_BODY.UI_APEX_SYNCHRONIZE.sql
show errors PACKAGE BODY "UI_APEX_SYNCHRONIZE"
prompt @@R__14.PACKAGE_BODY.UI_ERROR_PKG.sql
@@R__14.PACKAGE_BODY.UI_ERROR_PKG.sql
show errors PACKAGE BODY "UI_ERROR_PKG"
prompt @@R__14.PACKAGE_BODY.UI_SESSION_PKG.sql
@@R__14.PACKAGE_BODY.UI_SESSION_PKG.sql
show errors PACKAGE BODY "UI_SESSION_PKG"
prompt @@R__14.PACKAGE_BODY.UI_USER_MANAGEMENT_PKG.sql
@@R__14.PACKAGE_BODY.UI_USER_MANAGEMENT_PKG.sql
show errors PACKAGE BODY "UI_USER_MANAGEMENT_PKG"
prompt @@R__18.OBJECT_GRANT.UI_APEX_MESSAGES_PKG.sql
@@R__18.OBJECT_GRANT.UI_APEX_MESSAGES_PKG.sql
prompt @@R__18.OBJECT_GRANT.UI_USER_MANAGEMENT_PKG.sql
@@R__18.OBJECT_GRANT.UI_USER_MANAGEMENT_PKG.sql
prompt @@R__18.OBJECT_GRANT.UI_SESSION_PKG.sql
@@R__18.OBJECT_GRANT.UI_SESSION_PKG.sql
prompt @@R__18.OBJECT_GRANT.UI_ERROR_PKG.sql
@@R__18.OBJECT_GRANT.UI_ERROR_PKG.sql
prompt @@R__18.OBJECT_GRANT.UI_APEX_SYNCHRONIZE.sql
@@R__18.OBJECT_GRANT.UI_APEX_SYNCHRONIZE.sql
prompt @@30.PROCOBJ.UI_RESET_PWD_JOB.sql
@@30.PROCOBJ.UI_RESET_PWD_JOB.sql
