CREATE OR REPLACE VIEW GITHUB_INSTALLED_VERSIONS_V AS
select  V.ID
,       V.GITHUB_INSTALLED_PROJECTS_ID
,       ( SELECT P.GITHUB_REPO FROM GITHUB_INSTALLED_PROJECTS P WHERE P.ID = V.GITHUB_INSTALLED_PROJECTS_ID ) AS GITHUB_REPO
,       ( SELECT P.DIRECTORY_NAME FROM GITHUB_INSTALLED_PROJECTS P WHERE P.ID = V.GITHUB_INSTALLED_PROJECTS_ID ) AS DIRECTORY_NAME
,       ( SELECT P.OWNER FROM GITHUB_INSTALLED_PROJECTS P WHERE P.ID = V.GITHUB_INSTALLED_PROJECTS_ID ) AS OWNER
,       V.BASE_NAME
,       V.DATE_CREATED
,       V.CHECKSUM
,       V.BYTES
,       V.ERROR_MSG
        /* -1 for INSTALLED_RANK is the latest installed version per project id and base name, then -2, etcetera */
,       -1 * (ROW_NUMBER() OVER (PARTITION BY V.GITHUB_INSTALLED_PROJECTS_ID, V.BASE_NAME ORDER BY V.DATE_CREATED DESC)) AS INSTALLED_RANK
FROM    GITHUB_INSTALLED_VERSIONS V;
