CREATE TYPE "ORACLE_TOOLS"."T_OBJECT_INFO_REC" AUTHID DEFINER AS OBJECT
(OBJECT_SCHEMA VARCHAR2(128 BYTE),
OBJECT_TYPE VARCHAR2(30 BYTE),
OBJECT_NAME VARCHAR2(128 BYTE),
BASE_OBJECT_SCHEMA VARCHAR2(128 BYTE),
BASE_OBJECT_TYPE VARCHAR2(30 BYTE),
BASE_OBJECT_NAME VARCHAR2(128 BYTE),
COLUMN_NAME VARCHAR2(128 BYTE),
GRANTEE VARCHAR2(128 BYTE),
PRIVILEGE VARCHAR2(40 BYTE),
GRANTABLE VARCHAR2(3 BYTE));
/

