CREATE TABLE "ORACLE_TOOLS"."SCHEMA_OBJECT_FILTERS" 
   (	"ID" NUMBER(*,0) DEFAULT oracle_tools.schema_object_filters$seq.nextval CONSTRAINT "SCHEMA_OBJECT_FILTERS$NNC$ID" NOT NULL ENABLE, 
	"CREATED" TIMESTAMP (6) DEFAULT sys_extract_utc(systimestamp) CONSTRAINT "SCHEMA_OBJECT_FILTERS$NNC$CREATED" NOT NULL ENABLE, 
	"LAST_MODIFICATION_TIME_SCHEMA" DATE CONSTRAINT "SCHEMA_OBJECT_FILTERS$NNC$LAST_MODIFICATION_TIME_SCHEMA" NOT NULL ENABLE, 
	"UPDATED" TIMESTAMP (6), 
	"OBJ_JSON" CLOB CONSTRAINT "SCHEMA_OBJECT_FILTERS$NNC$OBJ_JSON" NOT NULL ENABLE, 
	"HASH_BUCKET" RAW(2000) CONSTRAINT "SCHEMA_OBJECT_FILTERS$NNC$HASH_BUCKET" NOT NULL ENABLE, 
	"HASH_BUCKET_NR" NUMBER(*,0) DEFAULT 1 CONSTRAINT "SCHEMA_OBJECT_FILTERS$NNC$HASH_BUCKET_NR" NOT NULL ENABLE, 
	 CONSTRAINT "SCHEMA_OBJECT_FILTERS$PK" PRIMARY KEY ("ID") ENABLE
   )  
  ORGANIZATION INDEX NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
  TABLESPACE "USERS" 
 PCTTHRESHOLD 50 INCLUDING "UPDATED" OVERFLOW
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 LOGGING
  TABLESPACE "USERS" 
 LOB ("OBJ_JSON") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES );

