CREATE TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_SCHEMA_DDLS" 
   (	"SESSION_ID" NUMBER NOT NULL ENABLE, 
	"SCHEMA_OBJECT_ID" VARCHAR2(500) NOT NULL ENABLE, 
	"DDL#" NUMBER(*,0) NOT NULL ENABLE, 
	"VERB" VARCHAR2(128) NOT NULL ENABLE, 
	"CREATED" TIMESTAMP (6) DEFAULT sys_extract_utc(systimestamp) NOT NULL ENABLE, 
	 CONSTRAINT "GENERATE_DDL_SESSION_SCHEMA_DDLS$PK" PRIMARY KEY ("SESSION_ID", "SCHEMA_OBJECT_ID", "DDL#") ENABLE
   )  
  ORGANIZATION INDEX NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
  TABLESPACE "USERS" 
 PCTTHRESHOLD 50 INCLUDING "CREATED" OVERFLOW
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 LOGGING
  TABLESPACE "USERS";

