CREATE TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_SCHEMA_OBJECTS" 
   (	"SESSION_ID" NUMBER CONSTRAINT "GENERATE_DDL_SESSION_SCHEMA_OBJECTS$NNC$SESSION_ID" NOT NULL ENABLE, 
	"SCHEMA_OBJECT_FILTER_ID" NUMBER(*,0) CONSTRAINT "GENERATE_DDL_SESSION_SCHEMA_OBJECTS$NNC$SCHEMA_OBJECT_FILTER_ID" NOT NULL ENABLE, 
	"SCHEMA_OBJECT_ID" VARCHAR2(500) CONSTRAINT "GENERATE_DDL_SESSION_SCHEMA_OBJECTS$NNC$SCHEMA_OBJECT_ID" NOT NULL ENABLE, 
	"CREATED" TIMESTAMP (6) DEFAULT sys_extract_utc(systimestamp) CONSTRAINT "GENERATE_DDL_SESSION_SCHEMA_OBJECTS$NNC$CREATED" NOT NULL ENABLE, 
	"LAST_DDL_TIME" DATE, 
	"GENERATE_DDL_CONFIGURATION_ID" NUMBER(*,0), 
	"DDL_OUTPUT_WRITTEN" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP"  
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA";

