CREATE TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_SCHEMA_DDL_CHUNKS" 
   (	"SESSION_ID" NUMBER NOT NULL ENABLE, 
	"SCHEMA_OBJECT_ID" VARCHAR2(500) NOT NULL ENABLE, 
	"DDL#" NUMBER(*,0) NOT NULL ENABLE, 
	"CHUNK#" NUMBER(*,0) NOT NULL ENABLE, 
	"CHUNK" VARCHAR2(4000 CHAR), 
	"CREATED" TIMESTAMP (6) DEFAULT sys_extract_utc(systimestamp) NOT NULL ENABLE
   )  
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "USERS";

