CREATE TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_BATCHES" 
   (	"SESSION_ID" NUMBER CONSTRAINT "GENERATE_DDL_SESSION_BATCHES$NNC$SESSION_ID" NOT NULL ENABLE, 
	"SEQ" NUMBER(*,0) CONSTRAINT "GENERATE_DDL_SESSION_BATCHES$NNC$SEQ" NOT NULL ENABLE, 
	"CREATED" TIMESTAMP (6) DEFAULT sys_extract_utc(systimestamp) CONSTRAINT "GENERATE_DDL_SESSION_BATCHES$NNC$CREATED" NOT NULL ENABLE, 
	"OBJECT_TYPE" VARCHAR2(30) CONSTRAINT "GENERATE_DDL_SESSION_BATCHES$NNC$OBJECT_TYPE" NOT NULL ENABLE, 
	"SCHEMA" VARCHAR2(128), 
	"TRANSFORM_PARAM_LIST" VARCHAR2(4000), 
	"PARAMS" CLOB, 
	"START_TIME" TIMESTAMP (6), 
	"END_TIME" TIMESTAMP (6), 
	"ERROR_MESSAGE" VARCHAR2(4000)
   )  
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "USERS" 
 LOB ("PARAMS") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  CACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES );

