CREATE TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_SCHEMA_OBJECTS" 
   (	"SESSION_ID" NUMBER NOT NULL ENABLE, 
	"SEQ" NUMBER(*,0) NOT NULL ENABLE, 
	"SCHEMA_OBJECT_FILTER_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"SCHEMA_OBJECT_ID" VARCHAR2(500) NOT NULL ENABLE, 
	"CREATED" TIMESTAMP (6) DEFAULT sys_extract_utc(systimestamp) NOT NULL ENABLE, 
	"LAST_DDL_TIME" DATE, 
	"GENERATE_DDL_CONFIGURATION_ID" NUMBER(*,0), 
	 CONSTRAINT "GENERATE_DDL_SESSION_SCHEMA_OBJECTS$PK" PRIMARY KEY ("SESSION_ID", "SEQ") ENABLE
   )  
  ORGANIZATION INDEX NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
  TABLESPACE "USERS" 
 PCTTHRESHOLD 50;

