CREATE TABLE "ORACLE_TOOLS"."GENERATE_DDL_CONFIGURATIONS" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"TRANSFORM_PARAM_LIST" VARCHAR2(4000) NOT NULL ENABLE, 
	"DB_VERSION" NUMBER NOT NULL ENABLE, 
	"LAST_DDL_TIME_SCHEMA" DATE NOT NULL ENABLE, 
	"CREATED" TIMESTAMP (6) DEFAULT sys_extract_utc(systimestamp) NOT NULL ENABLE
   )  
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "USERS";

