CREATE TABLE "ORACLE_TOOLS"."SCHEMA_OBJECTS" 
   (	"ID" VARCHAR2(500) CONSTRAINT "SCHEMA_OBJECTS$NNC$ID" NOT NULL ENABLE, 
	"OBJ" "ORACLE_TOOLS"."T_SCHEMA_OBJECT" , 
	"CREATED" TIMESTAMP (6) DEFAULT sys_extract_utc(systimestamp) CONSTRAINT "SCHEMA_OBJECTS$NNC$CREATED" NOT NULL ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"  
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" 
 NESTED TABLE TREAT("OBJ" AS "T_TABLE_COLUMN_OBJECT")."DATA_DEFAULT$" STORE AS "SYSNT-EX4O4=VZ+_VA4EM=$GDSWUB"
 (PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 LOGGING
 NOCOMPRESS 
  TABLESPACE "DATA" ) RETURN AS VALUE
 NESTED TABLE TREAT("OBJ" AS "T_TYPE_METHOD_OBJECT")."ARGUMENTS" STORE AS "SYSNT==NC#KWC-CM-OT1M=$GDSWUB"
 (PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 LOGGING
 NOCOMPRESS 
  TABLESPACE "DATA" ) RETURN AS VALUE;

