CREATE TABLE "ORACLE_TOOLS"."SCHEMA_OBJECT_FILTERS" 
   (	"ID" NUMBER(*,0) DEFAULT oracle_tools.schema_object_filters$seq.nextval NOT NULL ENABLE, 
	"CREATED" TIMESTAMP (6) DEFAULT sys_extract_utc(systimestamp) NOT NULL ENABLE, 
	"LAST_MODIFICATION_TIME_SCHEMA" DATE NOT NULL ENABLE, 
	"UPDATED" TIMESTAMP (6), 
	"OBJ" "ORACLE_TOOLS"."T_SCHEMA_OBJECT_FILTER" , 
	"HASH_BUCKET" RAW(2000) NOT NULL ENABLE, 
	"HASH_BUCKET_NR" NUMBER(*,0) DEFAULT 1 NOT NULL ENABLE, 
	 CONSTRAINT "SCHEMA_OBJECT_FILTERS$PK" PRIMARY KEY ("ID") ENABLE
   )  
  ORGANIZATION INDEX NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
  TABLESPACE "USERS" 
 PCTTHRESHOLD 50 INCLUDING "UPDATED" OVERFLOW
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 LOGGING
  TABLESPACE "USERS" 
 NESTED TABLE "OBJ"."OBJECT_TAB$" STORE AS "SCHEMA_OBJECT_FILTERS$OBJ$OBJECT_TAB$"
 (PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 LOGGING
 NOCOMPRESS 
  TABLESPACE "USERS" ) RETURN AS VALUE
 NESTED TABLE "OBJ"."OBJECT_CMP_TAB$" STORE AS "SCHEMA_OBJECT_FILTERS$OBJ$OBJECT_CMP_TAB$"
 (PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 LOGGING
 NOCOMPRESS 
  TABLESPACE "USERS" ) RETURN AS VALUE;

