CREATE TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_SCHEMA_OBJECTS" 
   (	"SESSION_ID" NUMBER CONSTRAINT "GENERATE_DDL_SESSION_SCHEMA_OBJECTS$NNC$SESSION_ID" NOT NULL ENABLE, 
	"SCHEMA_OBJECT_FILTER_ID" NUMBER(*,0) CONSTRAINT "GENERATE_DDL_SESSION_SCHEMA_OBJECTS$NNC$SCHEMA_OBJECT_FILTER_ID" NOT NULL ENABLE, 
	"SCHEMA_OBJECT_ID" VARCHAR2(500) CONSTRAINT "GENERATE_DDL_SESSION_SCHEMA_OBJECTS$NNC$SCHEMA_OBJECT_ID" NOT NULL ENABLE, 
	"CREATED" TIMESTAMP (6) DEFAULT sys_extract_utc(systimestamp) CONSTRAINT "GENERATE_DDL_SESSION_SCHEMA_OBJECTS$NNC$CREATED" NOT NULL ENABLE, 
	"LAST_DDL_TIME" DATE, 
	"GENERATE_DDL_CONFIGURATION_ID" NUMBER(*,0), 
	 CONSTRAINT "GENERATE_DDL_SESSION_SCHEMA_OBJECTS$PK" PRIMARY KEY ("SESSION_ID", "SCHEMA_OBJECT_ID") ENABLE
   )  
  ORGANIZATION INDEX NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
  TABLESPACE "USERS" 
 PCTTHRESHOLD 50;

