CREATE TABLE "ORACLE_TOOLS"."GENERATE_DDL_CONFIGURATIONS" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  CONSTRAINT "GENERATE_DDL_CONFIGURATIONS$NNC$ID" NOT NULL ENABLE, 
	"TRANSFORM_PARAM_LIST" VARCHAR2(4000) CONSTRAINT "GENERATE_DDL_CONFIGURATIONS$NNC$TRANSFORM_PARAM_LIST" NOT NULL ENABLE, 
	"DB_VERSION" NUMBER CONSTRAINT "GENERATE_DDL_CONFIGURATIONS$NNC$DB_VERSION" NOT NULL ENABLE, 
	"LAST_DDL_TIME_SCHEMA" DATE CONSTRAINT "GENERATE_DDL_CONFIGURATIONS$NNC$LAST_DDL_TIME_SCHEMA" NOT NULL ENABLE, 
	"CREATED" TIMESTAMP (6) DEFAULT sys_extract_utc(systimestamp) CONSTRAINT "GENERATE_DDL_CONFIGURATIONS$NNC$CREATED" NOT NULL ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"  
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA";

