CREATE INDEX "ORACLE_TOOLS"."GENERATE_DDL_SESSIONS$FK$1" ON "ORACLE_TOOLS"."GENERATE_DDL_SESSIONS" ("SCHEMA_OBJECT_FILTER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS";

CREATE INDEX "ORACLE_TOOLS"."GENERATE_DDL_SESSIONS$FK$2" ON "ORACLE_TOOLS"."GENERATE_DDL_SESSIONS" ("GENERATE_DDL_CONFIGURATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS";

