CREATE INDEX "ORACLE_TOOLS"."GENERATE_DDL_SESSIONS$IDX$1" ON "ORACLE_TOOLS"."GENERATE_DDL_SESSIONS" ("SCHEMA_OBJECT_FILTER_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA";

CREATE INDEX "ORACLE_TOOLS"."GENERATE_DDL_SESSIONS$IDX$2" ON "ORACLE_TOOLS"."GENERATE_DDL_SESSIONS" ("GENERATE_DDL_CONFIGURATION_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA";

