CREATE INDEX "ORACLE_TOOLS"."SCHEMA_OBJECTS$IDX$1" ON "ORACLE_TOOLS"."SCHEMA_OBJECTS" ("ORACLE_TOOLS"."T_SCHEMA_OBJECT"."OBJECT_SCHEMA"("OBJ"), "ORACLE_TOOLS"."T_SCHEMA_OBJECT"."OBJECT_NAME"("OBJ"), "ORACLE_TOOLS"."T_SCHEMA_OBJECT"."OBJECT_TYPE"("OBJ")) 
  PCTFREE 10 INITRANS 2 MAXTRANS 68 COMPUTE STATISTICS 
  TABLESPACE "USERS";

CREATE INDEX "ORACLE_TOOLS"."SCHEMA_OBJECTS$IDX$2" ON "ORACLE_TOOLS"."SCHEMA_OBJECTS" ("ORACLE_TOOLS"."T_SCHEMA_OBJECT"."BASE_OBJECT_SCHEMA"("OBJ"), "ORACLE_TOOLS"."T_SCHEMA_OBJECT"."BASE_OBJECT_NAME"("OBJ"), "ORACLE_TOOLS"."T_SCHEMA_OBJECT"."BASE_OBJECT_TYPE"("OBJ")) 
  PCTFREE 10 INITRANS 2 MAXTRANS 68 COMPUTE STATISTICS 
  TABLESPACE "USERS";

