CREATE INDEX "ORACLE_TOOLS"."GENERATE_DDL_SESSION_SCHEMA_OBJECTS$IDX$1" ON "ORACLE_TOOLS"."GENERATE_DDL_SESSION_SCHEMA_OBJECTS" ("SCHEMA_OBJECT_FILTER_ID", "SCHEMA_OBJECT_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA";

CREATE INDEX "ORACLE_TOOLS"."GENERATE_DDL_SESSION_SCHEMA_OBJECTS$IDX$2" ON "ORACLE_TOOLS"."GENERATE_DDL_SESSION_SCHEMA_OBJECTS" ("SESSION_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA";

CREATE INDEX "ORACLE_TOOLS"."GENERATE_DDL_SESSION_SCHEMA_OBJECTS$IDX$3" ON "ORACLE_TOOLS"."GENERATE_DDL_SESSION_SCHEMA_OBJECTS" ("SCHEMA_OBJECT_ID", "LAST_DDL_TIME", "GENERATE_DDL_CONFIGURATION_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA";

