ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_BATCHES" ADD CONSTRAINT "GENERATE_DDL_SESSION_BATCHES$PK" PRIMARY KEY ("SESSION_ID", "SEQ") ENABLE;

ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_BATCHES" ADD UNIQUE ("BASE_OBJECT_NAME_TAB") RELY ENABLE;

ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_BATCHES" ADD UNIQUE ("OBJECT_NAME_TAB") RELY ENABLE;

ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_BATCHES" MODIFY ("CREATED" NOT NULL ENABLE);

ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_BATCHES" MODIFY ("SEQ" NOT NULL ENABLE);

ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_BATCHES" MODIFY ("SESSION_ID" NOT NULL ENABLE);

