ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSIONS" ADD CONSTRAINT "GENERATE_DDL_SESSIONS$PK" PRIMARY KEY ("SESSION_ID") ENABLE;

ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSIONS" MODIFY ("CREATED" NOT NULL ENABLE);

ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSIONS" MODIFY ("SCHEMA_OBJECT_FILTER_ID" NOT NULL ENABLE);

ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSIONS" MODIFY ("SESSION_ID" NOT NULL ENABLE);

