ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_SCHEMA_DDLS" ADD CONSTRAINT "GENERATE_DDL_SESSION_SCHEMA_DDLS$CK$DDL#" CHECK (ddl# >= 1) ENABLE;

ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_SCHEMA_DDLS" ADD CONSTRAINT "GENERATE_DDL_SESSION_SCHEMA_DDLS$PK" PRIMARY KEY ("SESSION_ID", "SCHEMA_OBJECT_ID", "DDL#") ENABLE;

ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_SCHEMA_DDLS" MODIFY ("CREATED" NOT NULL ENABLE);

ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_SCHEMA_DDLS" MODIFY ("DDL#" NOT NULL ENABLE);

ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_SCHEMA_DDLS" MODIFY ("SCHEMA_OBJECT_ID" NOT NULL ENABLE);

ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_SCHEMA_DDLS" MODIFY ("SESSION_ID" NOT NULL ENABLE);

ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_SCHEMA_DDLS" MODIFY ("VERB" NOT NULL ENABLE);

