ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_SCHEMA_OBJECTS" ADD CONSTRAINT "GENERATE_DDL_SESSION_SCHEMA_OBJECTS$CK$SEQ" CHECK (seq >= 1) ENABLE;

ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_SCHEMA_OBJECTS" ADD CONSTRAINT "GENERATE_DDL_SESSION_SCHEMA_OBJECTS$PK" PRIMARY KEY ("SESSION_ID", "SEQ") ENABLE;

ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_SCHEMA_OBJECTS" ADD CONSTRAINT "GENERATE_DDL_SESSION_SCHEMA_OBJECTS$UK$1" UNIQUE ("SESSION_ID", "SCHEMA_OBJECT_ID") ENABLE;

ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_SCHEMA_OBJECTS" MODIFY ("CREATED" NOT NULL ENABLE);

ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_SCHEMA_OBJECTS" MODIFY ("SCHEMA_OBJECT_FILTER_ID" NOT NULL ENABLE);

ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_SCHEMA_OBJECTS" MODIFY ("SCHEMA_OBJECT_ID" NOT NULL ENABLE);

ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_SCHEMA_OBJECTS" MODIFY ("SEQ" NOT NULL ENABLE);

ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_SCHEMA_OBJECTS" MODIFY ("SESSION_ID" NOT NULL ENABLE);

