ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSIONS" ADD CONSTRAINT "GENERATE_DDL_SESSIONS$PK" PRIMARY KEY ("SESSION_ID") ENABLE;

ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSIONS" MODIFY ("CREATED" CONSTRAINT "GENERATE_DDL_SESSIONS$NNC$CREATED" NOT NULL ENABLE);

ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSIONS" MODIFY ("GENERATE_DDL_CONFIGURATION_ID" CONSTRAINT "GENERATE_DDL_SESSIONS$NNC$GENERATE_DDL_CONFIGURATION_ID" NOT NULL ENABLE);

ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSIONS" MODIFY ("SCHEMA_OBJECT_FILTER_ID" CONSTRAINT "GENERATE_DDL_SESSIONS$NNC$SCHEMA_OBJECT_FILTER_ID" NOT NULL ENABLE);

ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSIONS" MODIFY ("SESSION_ID" CONSTRAINT "GENERATE_DDL_SESSIONS$NNC$SESSION_ID" NOT NULL ENABLE);

ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSIONS" MODIFY ("USERNAME" CONSTRAINT "GENERATE_DDL_SESSIONS$NNC$USERNAME" NOT NULL ENABLE);

