ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_CONFIGURATIONS" ADD CONSTRAINT "GENERATE_DDL_CONFIGURATIONS$CK$1" CHECK (substr(transform_param_list, 1, 1) = ',') ENABLE;

ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_CONFIGURATIONS" ADD CONSTRAINT "GENERATE_DDL_CONFIGURATIONS$PK" PRIMARY KEY ("ID") ENABLE;

ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_CONFIGURATIONS" ADD CONSTRAINT "GENERATE_DDL_CONFIGURATIONS$UK$1" UNIQUE ("TRANSFORM_PARAM_LIST", "DB_VERSION", "LAST_DDL_TIME_SCHEMA") ENABLE;

ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_CONFIGURATIONS" MODIFY ("CREATED" CONSTRAINT "GENERATE_DDL_CONFIGURATIONS$NNC$CREATED" NOT NULL ENABLE);

ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_CONFIGURATIONS" MODIFY ("DB_VERSION" CONSTRAINT "GENERATE_DDL_CONFIGURATIONS$NNC$DB_VERSION" NOT NULL ENABLE);

ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_CONFIGURATIONS" MODIFY ("ID" CONSTRAINT "GENERATE_DDL_CONFIGURATIONS$NNC$ID" NOT NULL ENABLE);

ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_CONFIGURATIONS" MODIFY ("LAST_DDL_TIME_SCHEMA" CONSTRAINT "GENERATE_DDL_CONFIGURATIONS$NNC$LAST_DDL_TIME_SCHEMA" NOT NULL ENABLE);

ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_CONFIGURATIONS" MODIFY ("TRANSFORM_PARAM_LIST" CONSTRAINT "GENERATE_DDL_CONFIGURATIONS$NNC$TRANSFORM_PARAM_LIST" NOT NULL ENABLE);

