ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSIONS" ADD CONSTRAINT "GENERATE_DDL_SESSIONS$FK$1" FOREIGN KEY ("SCHEMA_OBJECT_FILTER_ID")
	  REFERENCES "ORACLE_TOOLS"."SCHEMA_OBJECT_FILTERS" ("ID") ON DELETE CASCADE ENABLE;

