ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_SCHEMA_DDL_CHUNKS" ADD CONSTRAINT "GENERATE_DDL_SESSION_SCHEMA_DDL_CHUNKS$FK$1" FOREIGN KEY ("SESSION_ID", "SCHEMA_OBJECT_ID", "DDL#")
	  REFERENCES "ORACLE_TOOLS"."GENERATE_DDL_SESSION_SCHEMA_DDLS" ("SESSION_ID", "SCHEMA_OBJECT_ID", "DDL#") ON DELETE CASCADE ENABLE;

