ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_SCHEMA_OBJECTS" ADD CONSTRAINT "GENERATE_DDL_SESSION_SCHEMA_OBJECTS$FK$1" FOREIGN KEY ("SCHEMA_OBJECT_FILTER_ID", "SCHEMA_OBJECT_ID")
	  REFERENCES "ORACLE_TOOLS"."SCHEMA_OBJECT_FILTER_RESULTS" ("SCHEMA_OBJECT_FILTER_ID", "SCHEMA_OBJECT_ID") ON DELETE CASCADE ENABLE;

ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_SCHEMA_OBJECTS" ADD CONSTRAINT "GENERATE_DDL_SESSION_SCHEMA_OBJECTS$FK$2" FOREIGN KEY ("SESSION_ID")
	  REFERENCES "ORACLE_TOOLS"."GENERATE_DDL_SESSIONS" ("SESSION_ID") ON DELETE CASCADE ENABLE;

