ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_SCHEMA_DDLS" ADD CONSTRAINT "GENERATE_DDL_SESSION_SCHEMA_DDLS$FK$1" FOREIGN KEY ("SESSION_ID", "SCHEMA_OBJECT_ID")
	  REFERENCES "ORACLE_TOOLS"."GENERATE_DDL_SESSION_SCHEMA_OBJECTS" ("SESSION_ID", "SCHEMA_OBJECT_ID") ON DELETE CASCADE ENABLE;

