whenever oserror exit failure
whenever sqlerror exit failure
set define off sqlblanklines on
ALTER SESSION SET PLSQL_WARNINGS = 'ENABLE:ALL';

prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_ARGUMENT_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_ARGUMENT_OBJECT.sql
show errors TYPE "T_ARGUMENT_OBJECT"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_ARGUMENT_OBJECT_TAB.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_ARGUMENT_OBJECT_TAB.sql
show errors TYPE "T_ARGUMENT_OBJECT_TAB"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_CLUSTER_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_CLUSTER_OBJECT.sql
show errors TYPE "T_CLUSTER_OBJECT"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_COMMENT_DDL.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_COMMENT_DDL.sql
show errors TYPE "T_COMMENT_DDL"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_COMMENT_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_COMMENT_OBJECT.sql
show errors TYPE "T_COMMENT_OBJECT"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_CONSTRAINT_DDL.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_CONSTRAINT_DDL.sql
show errors TYPE "T_CONSTRAINT_DDL"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_CONSTRAINT_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_CONSTRAINT_OBJECT.sql
show errors TYPE "T_CONSTRAINT_OBJECT"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_DDL.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_DDL.sql
show errors TYPE "T_DDL"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_DDL_SEQUENCE.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_DDL_SEQUENCE.sql
show errors TYPE "T_DDL_SEQUENCE"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_DDL_TAB.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_DDL_TAB.sql
show errors TYPE "T_DDL_TAB"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_DEPENDENT_OR_GRANTED_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_DEPENDENT_OR_GRANTED_OBJECT.sql
show errors TYPE "T_DEPENDENT_OR_GRANTED_OBJECT"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_FUNCTION_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_FUNCTION_OBJECT.sql
show errors TYPE "T_FUNCTION_OBJECT"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_INDEX_DDL.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_INDEX_DDL.sql
show errors TYPE "T_INDEX_DDL"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_INDEX_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_INDEX_OBJECT.sql
show errors TYPE "T_INDEX_OBJECT"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_JAVA_SOURCE_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_JAVA_SOURCE_OBJECT.sql
show errors TYPE "T_JAVA_SOURCE_OBJECT"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_MATERIALIZED_VIEW_DDL.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_MATERIALIZED_VIEW_DDL.sql
show errors TYPE "T_MATERIALIZED_VIEW_DDL"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_MATERIALIZED_VIEW_LOG_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_MATERIALIZED_VIEW_LOG_OBJECT.sql
show errors TYPE "T_MATERIALIZED_VIEW_LOG_OBJECT"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_MATERIALIZED_VIEW_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_MATERIALIZED_VIEW_OBJECT.sql
show errors TYPE "T_MATERIALIZED_VIEW_OBJECT"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_MEMBER_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_MEMBER_OBJECT.sql
show errors TYPE "T_MEMBER_OBJECT"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_NAMED_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_NAMED_OBJECT.sql
show errors TYPE "T_NAMED_OBJECT"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_OBJECT_GRANT_DDL.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_OBJECT_GRANT_DDL.sql
show errors TYPE "T_OBJECT_GRANT_DDL"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_OBJECT_GRANT_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_OBJECT_GRANT_OBJECT.sql
show errors TYPE "T_OBJECT_GRANT_OBJECT"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_OBJECT_INFO_REC.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_OBJECT_INFO_REC.sql
show errors TYPE "T_OBJECT_INFO_REC"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_OBJECT_INFO_TAB.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_OBJECT_INFO_TAB.sql
show errors TYPE "T_OBJECT_INFO_TAB"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_PACKAGE_BODY_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_PACKAGE_BODY_OBJECT.sql
show errors TYPE "T_PACKAGE_BODY_OBJECT"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_PACKAGE_SPEC_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_PACKAGE_SPEC_OBJECT.sql
show errors TYPE "T_PACKAGE_SPEC_OBJECT"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_PROCEDURE_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_PROCEDURE_OBJECT.sql
show errors TYPE "T_PROCEDURE_OBJECT"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_PROCOBJ_DDL.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_PROCOBJ_DDL.sql
show errors TYPE "T_PROCOBJ_DDL"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_PROCOBJ_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_PROCOBJ_OBJECT.sql
show errors TYPE "T_PROCOBJ_OBJECT"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_REFRESH_GROUP_DDL.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_REFRESH_GROUP_DDL.sql
show errors TYPE "T_REFRESH_GROUP_DDL"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_REFRESH_GROUP_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_REFRESH_GROUP_OBJECT.sql
show errors TYPE "T_REFRESH_GROUP_OBJECT"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_REF_CONSTRAINT_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_REF_CONSTRAINT_OBJECT.sql
show errors TYPE "T_REF_CONSTRAINT_OBJECT"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_SCHEMA_DDL.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_SCHEMA_DDL.sql
show errors TYPE "T_SCHEMA_DDL"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_SCHEMA_DDL_TAB.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_SCHEMA_DDL_TAB.sql
show errors TYPE "T_SCHEMA_DDL_TAB"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_SCHEMA_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_SCHEMA_OBJECT.sql
show errors TYPE "T_SCHEMA_OBJECT"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_SCHEMA_OBJECT_FILTER.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_SCHEMA_OBJECT_FILTER.sql
show errors TYPE "T_SCHEMA_OBJECT_FILTER"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_SCHEMA_OBJECT_TAB.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_SCHEMA_OBJECT_TAB.sql
show errors TYPE "T_SCHEMA_OBJECT_TAB"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_SEQUENCE_DDL.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_SEQUENCE_DDL.sql
show errors TYPE "T_SEQUENCE_DDL"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_SEQUENCE_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_SEQUENCE_OBJECT.sql
show errors TYPE "T_SEQUENCE_OBJECT"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_SYNONYM_DDL.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_SYNONYM_DDL.sql
show errors TYPE "T_SYNONYM_DDL"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_SYNONYM_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_SYNONYM_OBJECT.sql
show errors TYPE "T_SYNONYM_OBJECT"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_TABLE_COLUMN_DDL.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_TABLE_COLUMN_DDL.sql
show errors TYPE "T_TABLE_COLUMN_DDL"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_TABLE_COLUMN_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_TABLE_COLUMN_OBJECT.sql
show errors TYPE "T_TABLE_COLUMN_OBJECT"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_TABLE_DDL.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_TABLE_DDL.sql
show errors TYPE "T_TABLE_DDL"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_TABLE_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_TABLE_OBJECT.sql
show errors TYPE "T_TABLE_OBJECT"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_TEXT_TAB.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_TEXT_TAB.sql
show errors TYPE "T_TEXT_TAB"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_TRIGGER_DDL.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_TRIGGER_DDL.sql
show errors TYPE "T_TRIGGER_DDL"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_TRIGGER_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_TRIGGER_OBJECT.sql
show errors TYPE "T_TRIGGER_OBJECT"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_TYPE_ATTRIBUTE_DDL.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_TYPE_ATTRIBUTE_DDL.sql
show errors TYPE "T_TYPE_ATTRIBUTE_DDL"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_TYPE_ATTRIBUTE_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_TYPE_ATTRIBUTE_OBJECT.sql
show errors TYPE "T_TYPE_ATTRIBUTE_OBJECT"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_TYPE_BODY_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_TYPE_BODY_OBJECT.sql
show errors TYPE "T_TYPE_BODY_OBJECT"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_TYPE_METHOD_DDL.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_TYPE_METHOD_DDL.sql
show errors TYPE "T_TYPE_METHOD_DDL"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_TYPE_METHOD_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_TYPE_METHOD_OBJECT.sql
show errors TYPE "T_TYPE_METHOD_OBJECT"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_TYPE_SPEC_DDL.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_TYPE_SPEC_DDL.sql
show errors TYPE "T_TYPE_SPEC_DDL"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_TYPE_SPEC_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_TYPE_SPEC_OBJECT.sql
show errors TYPE "T_TYPE_SPEC_OBJECT"
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_VIEW_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_VIEW_OBJECT.sql
show errors TYPE "T_VIEW_OBJECT"
prompt @@R__08.ORACLE_TOOLS.FUNCTION.F_GENERATE_DDL.sql
@@R__08.ORACLE_TOOLS.FUNCTION.F_GENERATE_DDL.sql
show errors FUNCTION "F_GENERATE_DDL"
prompt @@R__09.ORACLE_TOOLS.PACKAGE_SPEC.PKG_DDL_ERROR.sql
@@R__09.ORACLE_TOOLS.PACKAGE_SPEC.PKG_DDL_ERROR.sql
show errors PACKAGE "PKG_DDL_ERROR"
prompt @@R__09.ORACLE_TOOLS.PACKAGE_SPEC.PKG_DDL_UTIL.sql
@@R__09.ORACLE_TOOLS.PACKAGE_SPEC.PKG_DDL_UTIL.sql
show errors PACKAGE "PKG_DDL_UTIL"
prompt @@R__09.ORACLE_TOOLS.PACKAGE_SPEC.PKG_SCHEMA_OBJECT_FILTER.sql
@@R__09.ORACLE_TOOLS.PACKAGE_SPEC.PKG_SCHEMA_OBJECT_FILTER.sql
show errors PACKAGE "PKG_SCHEMA_OBJECT_FILTER"
prompt @@R__09.ORACLE_TOOLS.PACKAGE_SPEC.PKG_STR_UTIL.sql
@@R__09.ORACLE_TOOLS.PACKAGE_SPEC.PKG_STR_UTIL.sql
show errors PACKAGE "PKG_STR_UTIL"
prompt @@R__10.ORACLE_TOOLS.VIEW.V_DISPLAY_DDL_SCHEMA.sql
@@R__10.ORACLE_TOOLS.VIEW.V_DISPLAY_DDL_SCHEMA.sql
show errors VIEW "V_DISPLAY_DDL_SCHEMA"
prompt @@R__10.ORACLE_TOOLS.VIEW.V_MY_INCLUDE_OBJECTS.sql
@@R__10.ORACLE_TOOLS.VIEW.V_MY_INCLUDE_OBJECTS.sql
show errors VIEW "V_MY_INCLUDE_OBJECTS"
prompt @@R__10.ORACLE_TOOLS.VIEW.V_MY_SCHEMA_DDL_INFO.sql
@@R__10.ORACLE_TOOLS.VIEW.V_MY_SCHEMA_DDL_INFO.sql
show errors VIEW "V_MY_SCHEMA_DDL_INFO"
prompt @@R__10.ORACLE_TOOLS.VIEW.V_MY_SCHEMA_OBJECT_INFO.sql
@@R__10.ORACLE_TOOLS.VIEW.V_MY_SCHEMA_OBJECT_INFO.sql
show errors VIEW "V_MY_SCHEMA_OBJECT_INFO"
prompt @@R__11.ORACLE_TOOLS.PROCEDURE.P_GENERATE_DDL.sql
@@R__11.ORACLE_TOOLS.PROCEDURE.P_GENERATE_DDL.sql
show errors PROCEDURE "P_GENERATE_DDL"
prompt @@R__14.ORACLE_TOOLS.PACKAGE_BODY.PKG_DDL_ERROR.sql
@@R__14.ORACLE_TOOLS.PACKAGE_BODY.PKG_DDL_ERROR.sql
show errors PACKAGE BODY "PKG_DDL_ERROR"
prompt @@R__14.ORACLE_TOOLS.PACKAGE_BODY.PKG_DDL_UTIL.sql
@@R__14.ORACLE_TOOLS.PACKAGE_BODY.PKG_DDL_UTIL.sql
show errors PACKAGE BODY "PKG_DDL_UTIL"
prompt @@R__14.ORACLE_TOOLS.PACKAGE_BODY.PKG_SCHEMA_OBJECT_FILTER.sql
@@R__14.ORACLE_TOOLS.PACKAGE_BODY.PKG_SCHEMA_OBJECT_FILTER.sql
show errors PACKAGE BODY "PKG_SCHEMA_OBJECT_FILTER"
prompt @@R__14.ORACLE_TOOLS.PACKAGE_BODY.PKG_STR_UTIL.sql
@@R__14.ORACLE_TOOLS.PACKAGE_BODY.PKG_STR_UTIL.sql
show errors PACKAGE BODY "PKG_STR_UTIL"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_ARGUMENT_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_ARGUMENT_OBJECT.sql
show errors TYPE BODY "T_ARGUMENT_OBJECT"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_CLUSTER_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_CLUSTER_OBJECT.sql
show errors TYPE BODY "T_CLUSTER_OBJECT"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_COMMENT_DDL.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_COMMENT_DDL.sql
show errors TYPE BODY "T_COMMENT_DDL"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_COMMENT_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_COMMENT_OBJECT.sql
show errors TYPE BODY "T_COMMENT_OBJECT"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_CONSTRAINT_DDL.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_CONSTRAINT_DDL.sql
show errors TYPE BODY "T_CONSTRAINT_DDL"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_CONSTRAINT_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_CONSTRAINT_OBJECT.sql
show errors TYPE BODY "T_CONSTRAINT_OBJECT"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_DDL.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_DDL.sql
show errors TYPE BODY "T_DDL"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_DDL_SEQUENCE.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_DDL_SEQUENCE.sql
show errors TYPE BODY "T_DDL_SEQUENCE"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_DEPENDENT_OR_GRANTED_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_DEPENDENT_OR_GRANTED_OBJECT.sql
show errors TYPE BODY "T_DEPENDENT_OR_GRANTED_OBJECT"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_FUNCTION_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_FUNCTION_OBJECT.sql
show errors TYPE BODY "T_FUNCTION_OBJECT"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_INDEX_DDL.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_INDEX_DDL.sql
show errors TYPE BODY "T_INDEX_DDL"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_INDEX_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_INDEX_OBJECT.sql
show errors TYPE BODY "T_INDEX_OBJECT"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_JAVA_SOURCE_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_JAVA_SOURCE_OBJECT.sql
show errors TYPE BODY "T_JAVA_SOURCE_OBJECT"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_MATERIALIZED_VIEW_DDL.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_MATERIALIZED_VIEW_DDL.sql
show errors TYPE BODY "T_MATERIALIZED_VIEW_DDL"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_MATERIALIZED_VIEW_LOG_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_MATERIALIZED_VIEW_LOG_OBJECT.sql
show errors TYPE BODY "T_MATERIALIZED_VIEW_LOG_OBJECT"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_MATERIALIZED_VIEW_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_MATERIALIZED_VIEW_OBJECT.sql
show errors TYPE BODY "T_MATERIALIZED_VIEW_OBJECT"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_MEMBER_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_MEMBER_OBJECT.sql
show errors TYPE BODY "T_MEMBER_OBJECT"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_NAMED_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_NAMED_OBJECT.sql
show errors TYPE BODY "T_NAMED_OBJECT"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_OBJECT_GRANT_DDL.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_OBJECT_GRANT_DDL.sql
show errors TYPE BODY "T_OBJECT_GRANT_DDL"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_OBJECT_GRANT_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_OBJECT_GRANT_OBJECT.sql
show errors TYPE BODY "T_OBJECT_GRANT_OBJECT"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_PACKAGE_BODY_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_PACKAGE_BODY_OBJECT.sql
show errors TYPE BODY "T_PACKAGE_BODY_OBJECT"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_PACKAGE_SPEC_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_PACKAGE_SPEC_OBJECT.sql
show errors TYPE BODY "T_PACKAGE_SPEC_OBJECT"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_PROCEDURE_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_PROCEDURE_OBJECT.sql
show errors TYPE BODY "T_PROCEDURE_OBJECT"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_PROCOBJ_DDL.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_PROCOBJ_DDL.sql
show errors TYPE BODY "T_PROCOBJ_DDL"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_PROCOBJ_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_PROCOBJ_OBJECT.sql
show errors TYPE BODY "T_PROCOBJ_OBJECT"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_REFRESH_GROUP_DDL.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_REFRESH_GROUP_DDL.sql
show errors TYPE BODY "T_REFRESH_GROUP_DDL"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_REFRESH_GROUP_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_REFRESH_GROUP_OBJECT.sql
show errors TYPE BODY "T_REFRESH_GROUP_OBJECT"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_REF_CONSTRAINT_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_REF_CONSTRAINT_OBJECT.sql
show errors TYPE BODY "T_REF_CONSTRAINT_OBJECT"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_SCHEMA_DDL.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_SCHEMA_DDL.sql
show errors TYPE BODY "T_SCHEMA_DDL"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_SCHEMA_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_SCHEMA_OBJECT.sql
show errors TYPE BODY "T_SCHEMA_OBJECT"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_SCHEMA_OBJECT_FILTER.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_SCHEMA_OBJECT_FILTER.sql
show errors TYPE BODY "T_SCHEMA_OBJECT_FILTER"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_SEQUENCE_DDL.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_SEQUENCE_DDL.sql
show errors TYPE BODY "T_SEQUENCE_DDL"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_SEQUENCE_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_SEQUENCE_OBJECT.sql
show errors TYPE BODY "T_SEQUENCE_OBJECT"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_SYNONYM_DDL.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_SYNONYM_DDL.sql
show errors TYPE BODY "T_SYNONYM_DDL"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_SYNONYM_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_SYNONYM_OBJECT.sql
show errors TYPE BODY "T_SYNONYM_OBJECT"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_TABLE_COLUMN_DDL.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_TABLE_COLUMN_DDL.sql
show errors TYPE BODY "T_TABLE_COLUMN_DDL"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_TABLE_COLUMN_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_TABLE_COLUMN_OBJECT.sql
show errors TYPE BODY "T_TABLE_COLUMN_OBJECT"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_TABLE_DDL.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_TABLE_DDL.sql
show errors TYPE BODY "T_TABLE_DDL"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_TABLE_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_TABLE_OBJECT.sql
show errors TYPE BODY "T_TABLE_OBJECT"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_TRIGGER_DDL.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_TRIGGER_DDL.sql
show errors TYPE BODY "T_TRIGGER_DDL"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_TRIGGER_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_TRIGGER_OBJECT.sql
show errors TYPE BODY "T_TRIGGER_OBJECT"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_TYPE_ATTRIBUTE_DDL.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_TYPE_ATTRIBUTE_DDL.sql
show errors TYPE BODY "T_TYPE_ATTRIBUTE_DDL"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_TYPE_ATTRIBUTE_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_TYPE_ATTRIBUTE_OBJECT.sql
show errors TYPE BODY "T_TYPE_ATTRIBUTE_OBJECT"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_TYPE_BODY_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_TYPE_BODY_OBJECT.sql
show errors TYPE BODY "T_TYPE_BODY_OBJECT"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_TYPE_METHOD_DDL.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_TYPE_METHOD_DDL.sql
show errors TYPE BODY "T_TYPE_METHOD_DDL"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_TYPE_METHOD_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_TYPE_METHOD_OBJECT.sql
show errors TYPE BODY "T_TYPE_METHOD_OBJECT"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_TYPE_SPEC_DDL.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_TYPE_SPEC_DDL.sql
show errors TYPE BODY "T_TYPE_SPEC_DDL"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_TYPE_SPEC_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_TYPE_SPEC_OBJECT.sql
show errors TYPE BODY "T_TYPE_SPEC_OBJECT"
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_VIEW_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_VIEW_OBJECT.sql
show errors TYPE BODY "T_VIEW_OBJECT"
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.F_GENERATE_DDL.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.F_GENERATE_DDL.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.PKG_DDL_ERROR.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.PKG_DDL_ERROR.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.PKG_DDL_UTIL.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.PKG_DDL_UTIL.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.PKG_SCHEMA_OBJECT_FILTER.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.PKG_SCHEMA_OBJECT_FILTER.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.PKG_STR_UTIL.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.PKG_STR_UTIL.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.P_GENERATE_DDL.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.P_GENERATE_DDL.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_ARGUMENT_OBJECT.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_ARGUMENT_OBJECT.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_ARGUMENT_OBJECT_TAB.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_ARGUMENT_OBJECT_TAB.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_CLUSTER_OBJECT.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_CLUSTER_OBJECT.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_COMMENT_DDL.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_COMMENT_DDL.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_COMMENT_OBJECT.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_COMMENT_OBJECT.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_CONSTRAINT_DDL.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_CONSTRAINT_DDL.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_CONSTRAINT_OBJECT.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_CONSTRAINT_OBJECT.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_DDL.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_DDL.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_DDL_SEQUENCE.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_DDL_SEQUENCE.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_DDL_TAB.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_DDL_TAB.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_DEPENDENT_OR_GRANTED_OBJECT.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_DEPENDENT_OR_GRANTED_OBJECT.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_FUNCTION_OBJECT.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_FUNCTION_OBJECT.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_INDEX_DDL.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_INDEX_DDL.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_INDEX_OBJECT.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_INDEX_OBJECT.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_JAVA_SOURCE_OBJECT.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_JAVA_SOURCE_OBJECT.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_MATERIALIZED_VIEW_DDL.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_MATERIALIZED_VIEW_DDL.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_MATERIALIZED_VIEW_LOG_OBJECT.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_MATERIALIZED_VIEW_LOG_OBJECT.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_MATERIALIZED_VIEW_OBJECT.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_MATERIALIZED_VIEW_OBJECT.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_MEMBER_OBJECT.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_MEMBER_OBJECT.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_NAMED_OBJECT.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_NAMED_OBJECT.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_OBJECT_GRANT_DDL.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_OBJECT_GRANT_DDL.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_OBJECT_GRANT_OBJECT.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_OBJECT_GRANT_OBJECT.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_OBJECT_INFO_REC.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_OBJECT_INFO_REC.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_OBJECT_INFO_TAB.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_OBJECT_INFO_TAB.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_PACKAGE_BODY_OBJECT.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_PACKAGE_BODY_OBJECT.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_PACKAGE_SPEC_OBJECT.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_PACKAGE_SPEC_OBJECT.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_PROCEDURE_OBJECT.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_PROCEDURE_OBJECT.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_PROCOBJ_DDL.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_PROCOBJ_DDL.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_PROCOBJ_OBJECT.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_PROCOBJ_OBJECT.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_REFRESH_GROUP_DDL.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_REFRESH_GROUP_DDL.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_REFRESH_GROUP_OBJECT.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_REFRESH_GROUP_OBJECT.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_REF_CONSTRAINT_OBJECT.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_REF_CONSTRAINT_OBJECT.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_SCHEMA_DDL.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_SCHEMA_DDL.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_SCHEMA_DDL_TAB.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_SCHEMA_DDL_TAB.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_SCHEMA_OBJECT.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_SCHEMA_OBJECT.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_SCHEMA_OBJECT_FILTER.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_SCHEMA_OBJECT_FILTER.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_SCHEMA_OBJECT_TAB.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_SCHEMA_OBJECT_TAB.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_SEQUENCE_DDL.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_SEQUENCE_DDL.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_SEQUENCE_OBJECT.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_SEQUENCE_OBJECT.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_SYNONYM_DDL.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_SYNONYM_DDL.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_SYNONYM_OBJECT.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_SYNONYM_OBJECT.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_TABLE_COLUMN_DDL.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_TABLE_COLUMN_DDL.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_TABLE_COLUMN_OBJECT.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_TABLE_COLUMN_OBJECT.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_TABLE_DDL.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_TABLE_DDL.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_TABLE_OBJECT.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_TABLE_OBJECT.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_TEXT_TAB.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_TEXT_TAB.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_TRIGGER_DDL.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_TRIGGER_DDL.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_TRIGGER_OBJECT.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_TRIGGER_OBJECT.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_TYPE_ATTRIBUTE_DDL.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_TYPE_ATTRIBUTE_DDL.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_TYPE_ATTRIBUTE_OBJECT.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_TYPE_ATTRIBUTE_OBJECT.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_TYPE_BODY_OBJECT.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_TYPE_BODY_OBJECT.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_TYPE_METHOD_DDL.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_TYPE_METHOD_DDL.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_TYPE_METHOD_OBJECT.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_TYPE_METHOD_OBJECT.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_TYPE_SPEC_DDL.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_TYPE_SPEC_DDL.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_TYPE_SPEC_OBJECT.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_TYPE_SPEC_OBJECT.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_VIEW_OBJECT.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_VIEW_OBJECT.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.V_DISPLAY_DDL_SCHEMA.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.V_DISPLAY_DDL_SCHEMA.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.V_MY_INCLUDE_OBJECTS.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.V_MY_INCLUDE_OBJECTS.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.V_MY_SCHEMA_DDL_INFO.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.V_MY_SCHEMA_DDL_INFO.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.V_MY_SCHEMA_OBJECT_INFO.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.V_MY_SCHEMA_OBJECT_INFO.sql
