whenever oserror exit failure
whenever sqlerror exit failure
set define off sqlblanklines on

prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_ARGUMENT_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_ARGUMENT_OBJECT.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_ARGUMENT_OBJECT_TAB.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_ARGUMENT_OBJECT_TAB.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_CLUSTER_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_CLUSTER_OBJECT.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_COMMENT_DDL.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_COMMENT_DDL.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_COMMENT_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_COMMENT_OBJECT.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_CONSTRAINT_DDL.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_CONSTRAINT_DDL.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_CONSTRAINT_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_CONSTRAINT_OBJECT.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_DDL.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_DDL.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_DDL_INFO_REC.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_DDL_INFO_REC.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_DDL_INFO_TAB.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_DDL_INFO_TAB.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_DDL_SEQUENCE.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_DDL_SEQUENCE.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_DDL_TAB.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_DDL_TAB.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_DEPENDENT_OR_GRANTED_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_DEPENDENT_OR_GRANTED_OBJECT.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_FUNCTION_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_FUNCTION_OBJECT.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_INDEX_DDL.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_INDEX_DDL.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_INDEX_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_INDEX_OBJECT.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_JAVA_SOURCE_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_JAVA_SOURCE_OBJECT.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_MATERIALIZED_VIEW_DDL.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_MATERIALIZED_VIEW_DDL.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_MATERIALIZED_VIEW_LOG_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_MATERIALIZED_VIEW_LOG_OBJECT.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_MATERIALIZED_VIEW_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_MATERIALIZED_VIEW_OBJECT.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_MEMBER_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_MEMBER_OBJECT.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_NAMED_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_NAMED_OBJECT.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_OBJECT_GRANT_DDL.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_OBJECT_GRANT_DDL.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_OBJECT_GRANT_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_OBJECT_GRANT_OBJECT.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_OBJECT_INFO_REC.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_OBJECT_INFO_REC.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_OBJECT_INFO_TAB.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_OBJECT_INFO_TAB.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_PACKAGE_BODY_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_PACKAGE_BODY_OBJECT.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_PACKAGE_SPEC_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_PACKAGE_SPEC_OBJECT.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_PROCEDURE_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_PROCEDURE_OBJECT.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_PROCOBJ_DDL.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_PROCOBJ_DDL.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_PROCOBJ_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_PROCOBJ_OBJECT.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_REFRESH_GROUP_DDL.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_REFRESH_GROUP_DDL.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_REFRESH_GROUP_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_REFRESH_GROUP_OBJECT.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_REF_CONSTRAINT_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_REF_CONSTRAINT_OBJECT.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_SCHEMA_DDL.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_SCHEMA_DDL.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_SCHEMA_DDL_TAB.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_SCHEMA_DDL_TAB.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_SCHEMA_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_SCHEMA_OBJECT.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_SCHEMA_OBJECT_TAB.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_SCHEMA_OBJECT_TAB.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_SEQUENCE_DDL.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_SEQUENCE_DDL.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_SEQUENCE_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_SEQUENCE_OBJECT.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_SORT_OBJECTS_BY_DEPS_REC.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_SORT_OBJECTS_BY_DEPS_REC.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_SORT_OBJECTS_BY_DEPS_TAB.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_SORT_OBJECTS_BY_DEPS_TAB.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_SYNONYM_DDL.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_SYNONYM_DDL.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_SYNONYM_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_SYNONYM_OBJECT.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_TABLE_COLUMN_DDL.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_TABLE_COLUMN_DDL.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_TABLE_COLUMN_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_TABLE_COLUMN_OBJECT.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_TABLE_DDL.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_TABLE_DDL.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_TABLE_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_TABLE_OBJECT.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_TEXT_TAB.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_TEXT_TAB.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_TRIGGER_DDL.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_TRIGGER_DDL.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_TRIGGER_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_TRIGGER_OBJECT.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_TYPE_ATTRIBUTE_DDL.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_TYPE_ATTRIBUTE_DDL.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_TYPE_ATTRIBUTE_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_TYPE_ATTRIBUTE_OBJECT.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_TYPE_BODY_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_TYPE_BODY_OBJECT.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_TYPE_METHOD_DDL.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_TYPE_METHOD_DDL.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_TYPE_METHOD_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_TYPE_METHOD_OBJECT.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_TYPE_SPEC_DDL.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_TYPE_SPEC_DDL.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_TYPE_SPEC_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_TYPE_SPEC_OBJECT.sql
prompt @@02.ORACLE_TOOLS.TYPE_SPEC.T_VIEW_OBJECT.sql
@@02.ORACLE_TOOLS.TYPE_SPEC.T_VIEW_OBJECT.sql
prompt @@R__08.ORACLE_TOOLS.FUNCTION.F_GENERATE_DDL.sql
@@R__08.ORACLE_TOOLS.FUNCTION.F_GENERATE_DDL.sql
prompt @@R__09.ORACLE_TOOLS.PACKAGE_SPEC.PKG_DATAPUMP_UTIL.sql
@@R__09.ORACLE_TOOLS.PACKAGE_SPEC.PKG_DATAPUMP_UTIL.sql
prompt @@R__09.ORACLE_TOOLS.PACKAGE_SPEC.PKG_DDL_UTIL.sql
@@R__09.ORACLE_TOOLS.PACKAGE_SPEC.PKG_DDL_UTIL.sql
prompt @@R__09.ORACLE_TOOLS.PACKAGE_SPEC.PKG_STR_UTIL.sql
@@R__09.ORACLE_TOOLS.PACKAGE_SPEC.PKG_STR_UTIL.sql
prompt @@R__10.ORACLE_TOOLS.VIEW.V_DISPLAY_DDL_SCHEMA.sql
@@R__10.ORACLE_TOOLS.VIEW.V_DISPLAY_DDL_SCHEMA.sql
prompt @@R__10.ORACLE_TOOLS.VIEW.V_MY_SCHEMA_DDL_INFO.sql
@@R__10.ORACLE_TOOLS.VIEW.V_MY_SCHEMA_DDL_INFO.sql
prompt @@R__10.ORACLE_TOOLS.VIEW.V_MY_SCHEMA_OBJECT_INFO.sql
@@R__10.ORACLE_TOOLS.VIEW.V_MY_SCHEMA_OBJECT_INFO.sql
prompt @@R__11.ORACLE_TOOLS.PROCEDURE.P_GENERATE_DDL.sql
@@R__11.ORACLE_TOOLS.PROCEDURE.P_GENERATE_DDL.sql
prompt @@R__14.ORACLE_TOOLS.PACKAGE_BODY.PKG_DATAPUMP_UTIL.sql
@@R__14.ORACLE_TOOLS.PACKAGE_BODY.PKG_DATAPUMP_UTIL.sql
prompt @@R__14.ORACLE_TOOLS.PACKAGE_BODY.PKG_DDL_UTIL.sql
@@R__14.ORACLE_TOOLS.PACKAGE_BODY.PKG_DDL_UTIL.sql
prompt @@R__14.ORACLE_TOOLS.PACKAGE_BODY.PKG_STR_UTIL.sql
@@R__14.ORACLE_TOOLS.PACKAGE_BODY.PKG_STR_UTIL.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_ARGUMENT_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_ARGUMENT_OBJECT.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_CLUSTER_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_CLUSTER_OBJECT.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_COMMENT_DDL.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_COMMENT_DDL.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_COMMENT_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_COMMENT_OBJECT.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_CONSTRAINT_DDL.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_CONSTRAINT_DDL.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_CONSTRAINT_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_CONSTRAINT_OBJECT.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_DDL.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_DDL.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_DDL_SEQUENCE.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_DDL_SEQUENCE.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_DEPENDENT_OR_GRANTED_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_DEPENDENT_OR_GRANTED_OBJECT.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_FUNCTION_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_FUNCTION_OBJECT.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_INDEX_DDL.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_INDEX_DDL.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_INDEX_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_INDEX_OBJECT.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_JAVA_SOURCE_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_JAVA_SOURCE_OBJECT.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_MATERIALIZED_VIEW_DDL.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_MATERIALIZED_VIEW_DDL.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_MATERIALIZED_VIEW_LOG_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_MATERIALIZED_VIEW_LOG_OBJECT.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_MATERIALIZED_VIEW_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_MATERIALIZED_VIEW_OBJECT.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_MEMBER_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_MEMBER_OBJECT.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_NAMED_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_NAMED_OBJECT.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_OBJECT_GRANT_DDL.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_OBJECT_GRANT_DDL.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_OBJECT_GRANT_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_OBJECT_GRANT_OBJECT.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_PACKAGE_BODY_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_PACKAGE_BODY_OBJECT.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_PACKAGE_SPEC_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_PACKAGE_SPEC_OBJECT.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_PROCEDURE_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_PROCEDURE_OBJECT.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_PROCOBJ_DDL.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_PROCOBJ_DDL.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_PROCOBJ_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_PROCOBJ_OBJECT.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_REFRESH_GROUP_DDL.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_REFRESH_GROUP_DDL.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_REFRESH_GROUP_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_REFRESH_GROUP_OBJECT.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_REF_CONSTRAINT_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_REF_CONSTRAINT_OBJECT.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_SCHEMA_DDL.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_SCHEMA_DDL.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_SCHEMA_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_SCHEMA_OBJECT.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_SEQUENCE_DDL.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_SEQUENCE_DDL.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_SEQUENCE_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_SEQUENCE_OBJECT.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_SYNONYM_DDL.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_SYNONYM_DDL.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_SYNONYM_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_SYNONYM_OBJECT.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_TABLE_COLUMN_DDL.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_TABLE_COLUMN_DDL.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_TABLE_COLUMN_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_TABLE_COLUMN_OBJECT.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_TABLE_DDL.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_TABLE_DDL.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_TABLE_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_TABLE_OBJECT.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_TRIGGER_DDL.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_TRIGGER_DDL.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_TRIGGER_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_TRIGGER_OBJECT.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_TYPE_ATTRIBUTE_DDL.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_TYPE_ATTRIBUTE_DDL.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_TYPE_ATTRIBUTE_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_TYPE_ATTRIBUTE_OBJECT.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_TYPE_BODY_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_TYPE_BODY_OBJECT.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_TYPE_METHOD_DDL.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_TYPE_METHOD_DDL.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_TYPE_METHOD_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_TYPE_METHOD_OBJECT.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_TYPE_SPEC_DDL.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_TYPE_SPEC_DDL.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_TYPE_SPEC_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_TYPE_SPEC_OBJECT.sql
prompt @@R__15.ORACLE_TOOLS.TYPE_BODY.T_VIEW_OBJECT.sql
@@R__15.ORACLE_TOOLS.TYPE_BODY.T_VIEW_OBJECT.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.PKG_DDL_UTIL.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.PKG_DDL_UTIL.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.PKG_STR_UTIL.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.PKG_STR_UTIL.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.P_GENERATE_DDL.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.P_GENERATE_DDL.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_DDL.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_DDL.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_SCHEMA_OBJECT.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_SCHEMA_OBJECT.sql
prompt @@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_TEXT_TAB.sql
@@R__18.ORACLE_TOOLS.OBJECT_GRANT.T_TEXT_TAB.sql
