call dbms_application_info.set_module('R__18.ORACLE_TOOLS.OBJECT_GRANT.V_MY_GENERATE_DDL_SESSION_BATCHES_NO_SCHEMA_EXPORT.sql', null);
call dbms_application_info.set_action('SQL statement 1');
GRANT SELECT ON "ORACLE_TOOLS"."V_MY_GENERATE_DDL_SESSION_BATCHES_NO_SCHEMA_EXPORT" TO PUBLIC;

