/* perl generate_ddl.pl (version 2023-01-05) --nodynamic-sql --force-view --group-constraints --skip-install-sql --source-schema=ORACLE_TOOLS --nostrip-source-schema */

/*
-- JDBC url - username : jdbc:oracle:thin:@//127.0.0.1:1521/freepdb1 - BC_PROXY[ORACLE_TOOLS]
-- source schema       : 
-- source database link: 
-- target schema       : ORACLE_TOOLS
-- target database link: 
-- object type         : 
-- object names include: 1
-- object names        : F_GENERATE_DDL
,GENERATE_DDL_CONFIGURATIONS
,GENERATE_DDL_SESSIONS
,GENERATE_DDL_SESSION_BATCHES
,GENERATE_DDL_SESSION_SCHEMA_OBJECTS
,GENERATE_DDLS
,GENERATE_DDL_STATEMENTS
,GENERATE_DDL_STATEMENT_CHUNKS
,PKG_DDL_ERROR
,PKG_DDL_UTIL
,PKG_REPLICATE_UTIL
,PKG_SCHEMA_OBJECT_FILTER
,PKG_STR_UTIL
,P_GENERATE_DDL
,SCHEMA_OBJECTS
,SCHEMA_OBJECTS_API
,SCHEMA_OBJECT_FILTERS
,SCHEMA_OBJECT_FILTERS$SEQ
,SCHEMA_OBJECT_FILTER_RESULTS
,T_ARGUMENT_OBJECT
,T_ARGUMENT_OBJECT_TAB
,T_CLUSTER_OBJECT
,T_COMMENT_DDL
,T_COMMENT_OBJECT
,T_CONSTRAINT_DDL
,T_CONSTRAINT_OBJECT
,T_DDL
,T_DDL_SEQUENCE
,T_DDL_TAB
,T_DEPENDENT_OR_GRANTED_OBJECT
,T_DISPLAY_DDL_SQL_REC
,T_DISPLAY_DDL_SQL_TAB
,T_FUNCTION_OBJECT
,T_INDEX_DDL
,T_INDEX_OBJECT
,T_JAVA_SOURCE_OBJECT
,T_MATERIALIZED_VIEW_DDL
,T_MATERIALIZED_VIEW_LOG_OBJECT
,T_MATERIALIZED_VIEW_OBJECT
,T_MEMBER_OBJECT
,T_NAMED_OBJECT
,T_OBJECT_GRANT_DDL
,T_OBJECT_GRANT_OBJECT
,T_PACKAGE_BODY_OBJECT
,T_PACKAGE_SPEC_OBJECT
,T_PROCEDURE_OBJECT
,T_PROCOBJ_DDL
,T_PROCOBJ_OBJECT
,T_REFRESH_GROUP_DDL
,T_REFRESH_GROUP_OBJECT
,T_REF_CONSTRAINT_OBJECT
,T_SCHEMA_DDL
,T_SCHEMA_DDL_TAB
,T_SCHEMA_OBJECT
,T_SCHEMA_OBJECT_FILTER
,T_SCHEMA_OBJECT_TAB
,T_SEQUENCE_DDL
,T_SEQUENCE_OBJECT
,T_SYNONYM_DDL
,T_SYNONYM_OBJECT
,T_TABLE_COLUMN_DDL
,T_TABLE_COLUMN_OBJECT
,T_TABLE_DDL
,T_TABLE_OBJECT
,T_TEXT_TAB
,T_TRIGGER_DDL
,T_TRIGGER_OBJECT
,T_TYPE_ATTRIBUTE_DDL
,T_TYPE_ATTRIBUTE_OBJECT
,T_TYPE_BODY_OBJECT
,T_TYPE_METHOD_DDL
,T_TYPE_METHOD_OBJECT
,T_TYPE_SPEC_DDL
,T_TYPE_SPEC_OBJECT
,T_VIEW_OBJECT
,V_ALL_SCHEMA_OBJECTS
,V_DISPLAY_DDL_SQL
,V_MY_COMMENTS_DICT
,V_MY_CONSTRAINTS_DICT
,V_MY_GENERATE_DDL_SESSION_SCHEMA_DDL_BATCHES
,V_MY_INCLUDE_OBJECTS
,V_MY_NAMED_SCHEMA_OBJECTS
,V_MY_OBJECT_GRANTS_DICT
,V_MY_SCHEMA_DDLS
,V_MY_SCHEMA_OBJECTS
,V_MY_SCHEMA_OBJECTS_NO_DDL_YET
,V_MY_SCHEMA_OBJECT_FILTER
,V_MY_SCHEMA_OBJECT_INFO
-- skip repeatables    : 0
-- interface           : pkg_ddl_util v4
-- transform params    : 
-- exclude objects     : 
-- include objects     : 
-- owner               : ORACLE_TOOLS
*/
-- pkg_ddl_util v4
call dbms_application_info.set_module('uninstall.sql', null);
/* SQL statement 1 (ALTER;ORACLE_TOOLS;REF_CONSTRAINT;SCHEMA_OBJECT_FILTER_RESULTS$FK$2;ORACLE_TOOLS;TABLE;SCHEMA_OBJECT_FILTER_RESULTS;;;;;2) */
call dbms_application_info.set_action('SQL statement 1');
ALTER TABLE "ORACLE_TOOLS"."SCHEMA_OBJECT_FILTER_RESULTS" DROP CONSTRAINT SCHEMA_OBJECT_FILTER_RESULTS$FK$2;

/* SQL statement 2 (ALTER;ORACLE_TOOLS;REF_CONSTRAINT;SCHEMA_OBJECT_FILTER_RESULTS$FK$1;ORACLE_TOOLS;TABLE;SCHEMA_OBJECT_FILTER_RESULTS;;;;;2) */
call dbms_application_info.set_action('SQL statement 2');
ALTER TABLE "ORACLE_TOOLS"."SCHEMA_OBJECT_FILTER_RESULTS" DROP CONSTRAINT SCHEMA_OBJECT_FILTER_RESULTS$FK$1;

/* SQL statement 3 (ALTER;ORACLE_TOOLS;REF_CONSTRAINT;GENERATE_DDL_SESSION_SCHEMA_OBJECTS$FK$3;ORACLE_TOOLS;TABLE;GENERATE_DDL_SESSION_SCHEMA_OBJECTS;;;;;2) */
call dbms_application_info.set_action('SQL statement 3');
ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_SCHEMA_OBJECTS" DROP CONSTRAINT GENERATE_DDL_SESSION_SCHEMA_OBJECTS$FK$3;

/* SQL statement 4 (ALTER;ORACLE_TOOLS;REF_CONSTRAINT;GENERATE_DDL_SESSION_SCHEMA_OBJECTS$FK$2;ORACLE_TOOLS;TABLE;GENERATE_DDL_SESSION_SCHEMA_OBJECTS;;;;;2) */
call dbms_application_info.set_action('SQL statement 4');
ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_SCHEMA_OBJECTS" DROP CONSTRAINT GENERATE_DDL_SESSION_SCHEMA_OBJECTS$FK$2;

/* SQL statement 5 (ALTER;ORACLE_TOOLS;REF_CONSTRAINT;GENERATE_DDL_SESSION_SCHEMA_OBJECTS$FK$1;ORACLE_TOOLS;TABLE;GENERATE_DDL_SESSION_SCHEMA_OBJECTS;;;;;2) */
call dbms_application_info.set_action('SQL statement 5');
ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_SCHEMA_OBJECTS" DROP CONSTRAINT GENERATE_DDL_SESSION_SCHEMA_OBJECTS$FK$1;

/* SQL statement 6 (ALTER;ORACLE_TOOLS;REF_CONSTRAINT;GENERATE_DDL_SESSION_BATCHES$FK$1;ORACLE_TOOLS;TABLE;GENERATE_DDL_SESSION_BATCHES;;;;;2) */
call dbms_application_info.set_action('SQL statement 6');
ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_BATCHES" DROP CONSTRAINT GENERATE_DDL_SESSION_BATCHES$FK$1;

/* SQL statement 7 (ALTER;ORACLE_TOOLS;REF_CONSTRAINT;GENERATE_DDL_SESSIONS$FK$2;ORACLE_TOOLS;TABLE;GENERATE_DDL_SESSIONS;;;;;2) */
call dbms_application_info.set_action('SQL statement 7');
ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSIONS" DROP CONSTRAINT GENERATE_DDL_SESSIONS$FK$2;

/* SQL statement 8 (ALTER;ORACLE_TOOLS;REF_CONSTRAINT;GENERATE_DDL_SESSIONS$FK$1;ORACLE_TOOLS;TABLE;GENERATE_DDL_SESSIONS;;;;;2) */
call dbms_application_info.set_action('SQL statement 8');
ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSIONS" DROP CONSTRAINT GENERATE_DDL_SESSIONS$FK$1;

/* SQL statement 9 (ALTER;ORACLE_TOOLS;CONSTRAINT;SYS_C0022152;ORACLE_TOOLS;TABLE;GENERATE_DDL_SESSION_SCHEMA_OBJECTS;;;;;2) */
call dbms_application_info.set_action('SQL statement 9');
ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_SCHEMA_OBJECTS" DROP CONSTRAINT SYS_C0022152;

/* SQL statement 10 (ALTER;ORACLE_TOOLS;CONSTRAINT;SYS_C0022151;ORACLE_TOOLS;TABLE;GENERATE_DDL_SESSION_SCHEMA_OBJECTS;;;;;2) */
call dbms_application_info.set_action('SQL statement 10');
ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_SCHEMA_OBJECTS" DROP CONSTRAINT SYS_C0022151;

/* SQL statement 11 (ALTER;ORACLE_TOOLS;CONSTRAINT;SYS_C0022150;ORACLE_TOOLS;TABLE;GENERATE_DDL_SESSION_SCHEMA_OBJECTS;;;;;2) */
call dbms_application_info.set_action('SQL statement 11');
ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_SCHEMA_OBJECTS" DROP CONSTRAINT SYS_C0022150;

/* SQL statement 12 (ALTER;ORACLE_TOOLS;CONSTRAINT;SYS_C0022149;ORACLE_TOOLS;TABLE;GENERATE_DDL_SESSION_SCHEMA_OBJECTS;;;;;2) */
call dbms_application_info.set_action('SQL statement 12');
ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_SCHEMA_OBJECTS" DROP CONSTRAINT SYS_C0022149;

/* SQL statement 13 (ALTER;ORACLE_TOOLS;CONSTRAINT;SYS_C0022148;ORACLE_TOOLS;TABLE;GENERATE_DDL_SESSION_SCHEMA_OBJECTS;;;;;2) */
call dbms_application_info.set_action('SQL statement 13');
ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_SCHEMA_OBJECTS" DROP CONSTRAINT SYS_C0022148;

/* SQL statement 14 (ALTER;ORACLE_TOOLS;CONSTRAINT;SYS_C0022137;ORACLE_TOOLS;TABLE;GENERATE_DDL_SESSION_BATCHES;;;;;2) */
call dbms_application_info.set_action('SQL statement 14');
ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_BATCHES" DROP UNIQUE ("SYS_NC0001000011$") KEEP INDEX;

/* SQL statement 15 (ALTER;ORACLE_TOOLS;CONSTRAINT;SYS_C0022136;ORACLE_TOOLS;TABLE;GENERATE_DDL_SESSION_BATCHES;;;;;2) */
call dbms_application_info.set_action('SQL statement 15');
ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_BATCHES" DROP UNIQUE ("SYS_NC0001200013$") KEEP INDEX;

/* SQL statement 16 (ALTER;ORACLE_TOOLS;CONSTRAINT;SYS_C0022134;ORACLE_TOOLS;TABLE;GENERATE_DDL_SESSION_BATCHES;;;;;2) */
call dbms_application_info.set_action('SQL statement 16');
ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_BATCHES" DROP CONSTRAINT SYS_C0022134;

/* SQL statement 17 (ALTER;ORACLE_TOOLS;CONSTRAINT;SYS_C0022133;ORACLE_TOOLS;TABLE;GENERATE_DDL_SESSION_BATCHES;;;;;2) */
call dbms_application_info.set_action('SQL statement 17');
ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_BATCHES" DROP CONSTRAINT SYS_C0022133;

/* SQL statement 18 (ALTER;ORACLE_TOOLS;CONSTRAINT;SYS_C0022132;ORACLE_TOOLS;TABLE;GENERATE_DDL_SESSION_BATCHES;;;;;2) */
call dbms_application_info.set_action('SQL statement 18');
ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_BATCHES" DROP CONSTRAINT SYS_C0022132;

/* SQL statement 19 (ALTER;ORACLE_TOOLS;CONSTRAINT;SYS_C0022128;ORACLE_TOOLS;TABLE;GENERATE_DDL_SESSIONS;;;;;2) */
call dbms_application_info.set_action('SQL statement 19');
ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSIONS" DROP CONSTRAINT SYS_C0022128;

/* SQL statement 20 (ALTER;ORACLE_TOOLS;CONSTRAINT;SYS_C0022127;ORACLE_TOOLS;TABLE;GENERATE_DDL_SESSIONS;;;;;2) */
call dbms_application_info.set_action('SQL statement 20');
ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSIONS" DROP CONSTRAINT SYS_C0022127;

/* SQL statement 21 (ALTER;ORACLE_TOOLS;CONSTRAINT;SYS_C0022126;ORACLE_TOOLS;TABLE;GENERATE_DDL_SESSIONS;;;;;2) */
call dbms_application_info.set_action('SQL statement 21');
ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSIONS" DROP CONSTRAINT SYS_C0022126;

/* SQL statement 22 (ALTER;ORACLE_TOOLS;CONSTRAINT;SYS_C0022125;ORACLE_TOOLS;TABLE;GENERATE_DDL_SESSIONS;;;;;2) */
call dbms_application_info.set_action('SQL statement 22');
ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSIONS" DROP CONSTRAINT SYS_C0022125;

/* SQL statement 23 (ALTER;ORACLE_TOOLS;CONSTRAINT;SYS_C0022120;ORACLE_TOOLS;TABLE;SCHEMA_OBJECT_FILTER_RESULTS;;;;;2) */
call dbms_application_info.set_action('SQL statement 23');
ALTER TABLE "ORACLE_TOOLS"."SCHEMA_OBJECT_FILTER_RESULTS" DROP CONSTRAINT SYS_C0022120;

/* SQL statement 24 (ALTER;ORACLE_TOOLS;CONSTRAINT;SYS_C0022119;ORACLE_TOOLS;TABLE;SCHEMA_OBJECT_FILTER_RESULTS;;;;;2) */
call dbms_application_info.set_action('SQL statement 24');
ALTER TABLE "ORACLE_TOOLS"."SCHEMA_OBJECT_FILTER_RESULTS" DROP CONSTRAINT SYS_C0022119;

/* SQL statement 25 (ALTER;ORACLE_TOOLS;CONSTRAINT;SYS_C0022118;ORACLE_TOOLS;TABLE;SCHEMA_OBJECT_FILTER_RESULTS;;;;;2) */
call dbms_application_info.set_action('SQL statement 25');
ALTER TABLE "ORACLE_TOOLS"."SCHEMA_OBJECT_FILTER_RESULTS" DROP CONSTRAINT SYS_C0022118;

/* SQL statement 26 (ALTER;ORACLE_TOOLS;CONSTRAINT;SYS_C0022117;ORACLE_TOOLS;TABLE;SCHEMA_OBJECT_FILTER_RESULTS;;;;;2) */
call dbms_application_info.set_action('SQL statement 26');
ALTER TABLE "ORACLE_TOOLS"."SCHEMA_OBJECT_FILTER_RESULTS" DROP CONSTRAINT SYS_C0022117;

/* SQL statement 27 (ALTER;ORACLE_TOOLS;CONSTRAINT;SYS_C0022113;ORACLE_TOOLS;TABLE;GENERATE_DDL_CONFIGURATIONS;;;;;2) */
call dbms_application_info.set_action('SQL statement 27');
ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_CONFIGURATIONS" DROP CONSTRAINT SYS_C0022113;

/* SQL statement 28 (ALTER;ORACLE_TOOLS;CONSTRAINT;SYS_C0022112;ORACLE_TOOLS;TABLE;GENERATE_DDL_CONFIGURATIONS;;;;;2) */
call dbms_application_info.set_action('SQL statement 28');
ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_CONFIGURATIONS" DROP CONSTRAINT SYS_C0022112;

/* SQL statement 29 (ALTER;ORACLE_TOOLS;CONSTRAINT;SYS_C0022111;ORACLE_TOOLS;TABLE;GENERATE_DDL_CONFIGURATIONS;;;;;2) */
call dbms_application_info.set_action('SQL statement 29');
ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_CONFIGURATIONS" DROP CONSTRAINT SYS_C0022111;

/* SQL statement 30 (ALTER;ORACLE_TOOLS;CONSTRAINT;SYS_C0022110;ORACLE_TOOLS;TABLE;GENERATE_DDL_CONFIGURATIONS;;;;;2) */
call dbms_application_info.set_action('SQL statement 30');
ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_CONFIGURATIONS" DROP CONSTRAINT SYS_C0022110;

/* SQL statement 31 (ALTER;ORACLE_TOOLS;CONSTRAINT;SYS_C0022109;ORACLE_TOOLS;TABLE;GENERATE_DDL_CONFIGURATIONS;;;;;2) */
call dbms_application_info.set_action('SQL statement 31');
ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_CONFIGURATIONS" DROP CONSTRAINT SYS_C0022109;

/* SQL statement 32 (ALTER;ORACLE_TOOLS;CONSTRAINT;SYS_C0022108;ORACLE_TOOLS;TABLE;SCHEMA_OBJECTS;;;;;2) */
call dbms_application_info.set_action('SQL statement 32');
ALTER TABLE "ORACLE_TOOLS"."SCHEMA_OBJECTS" DROP UNIQUE ("SYS_NC0003600037$") KEEP INDEX;

/* SQL statement 33 (ALTER;ORACLE_TOOLS;CONSTRAINT;SYS_C0022107;ORACLE_TOOLS;TABLE;SCHEMA_OBJECTS;;;;;2) */
call dbms_application_info.set_action('SQL statement 33');
ALTER TABLE "ORACLE_TOOLS"."SCHEMA_OBJECTS" DROP UNIQUE ("SYS_NC0004700048$") KEEP INDEX;

/* SQL statement 34 (ALTER;ORACLE_TOOLS;CONSTRAINT;SYS_C0022104;ORACLE_TOOLS;TABLE;SCHEMA_OBJECTS;;;;;2) */
call dbms_application_info.set_action('SQL statement 34');
ALTER TABLE "ORACLE_TOOLS"."SCHEMA_OBJECTS" DROP CONSTRAINT SYS_C0022104;

/* SQL statement 35 (ALTER;ORACLE_TOOLS;CONSTRAINT;SYS_C0022103;ORACLE_TOOLS;TABLE;SCHEMA_OBJECTS;;;;;2) */
call dbms_application_info.set_action('SQL statement 35');
ALTER TABLE "ORACLE_TOOLS"."SCHEMA_OBJECTS" DROP CONSTRAINT SYS_C0022103;

/* SQL statement 36 (ALTER;ORACLE_TOOLS;CONSTRAINT;SYS_C0022101;ORACLE_TOOLS;TABLE;SCHEMA_OBJECT_FILTERS;;;;;2) */
call dbms_application_info.set_action('SQL statement 36');
ALTER TABLE "ORACLE_TOOLS"."SCHEMA_OBJECT_FILTERS" DROP UNIQUE ("SYS_NC0000800009$") KEEP INDEX;

/* SQL statement 37 (ALTER;ORACLE_TOOLS;CONSTRAINT;SYS_C0022100;ORACLE_TOOLS;TABLE;SCHEMA_OBJECT_FILTERS;;;;;2) */
call dbms_application_info.set_action('SQL statement 37');
ALTER TABLE "ORACLE_TOOLS"."SCHEMA_OBJECT_FILTERS" DROP UNIQUE ("SYS_NC0001000011$") KEEP INDEX;

/* SQL statement 38 (ALTER;ORACLE_TOOLS;CONSTRAINT;SYS_C0022096;ORACLE_TOOLS;TABLE;SCHEMA_OBJECT_FILTERS;;;;;2) */
call dbms_application_info.set_action('SQL statement 38');
ALTER TABLE "ORACLE_TOOLS"."SCHEMA_OBJECT_FILTERS" DROP CONSTRAINT SYS_C0022096;

/* SQL statement 39 (ALTER;ORACLE_TOOLS;CONSTRAINT;SYS_C0022095;ORACLE_TOOLS;TABLE;SCHEMA_OBJECT_FILTERS;;;;;2) */
call dbms_application_info.set_action('SQL statement 39');
ALTER TABLE "ORACLE_TOOLS"."SCHEMA_OBJECT_FILTERS" DROP CONSTRAINT SYS_C0022095;

/* SQL statement 40 (ALTER;ORACLE_TOOLS;CONSTRAINT;SYS_C0022094;ORACLE_TOOLS;TABLE;SCHEMA_OBJECT_FILTERS;;;;;2) */
call dbms_application_info.set_action('SQL statement 40');
ALTER TABLE "ORACLE_TOOLS"."SCHEMA_OBJECT_FILTERS" DROP CONSTRAINT SYS_C0022094;

/* SQL statement 41 (ALTER;ORACLE_TOOLS;CONSTRAINT;SYS_C0022093;ORACLE_TOOLS;TABLE;SCHEMA_OBJECT_FILTERS;;;;;2) */
call dbms_application_info.set_action('SQL statement 41');
ALTER TABLE "ORACLE_TOOLS"."SCHEMA_OBJECT_FILTERS" DROP CONSTRAINT SYS_C0022093;

/* SQL statement 42 (ALTER;ORACLE_TOOLS;CONSTRAINT;SYS_C0022092;ORACLE_TOOLS;TABLE;SCHEMA_OBJECT_FILTERS;;;;;2) */
call dbms_application_info.set_action('SQL statement 42');
ALTER TABLE "ORACLE_TOOLS"."SCHEMA_OBJECT_FILTERS" DROP CONSTRAINT SYS_C0022092;

/* SQL statement 43 (ALTER;ORACLE_TOOLS;CONSTRAINT;SCHEMA_OBJECT_FILTER_RESULTS$PK;ORACLE_TOOLS;TABLE;SCHEMA_OBJECT_FILTER_RESULTS;;;;;2) */
call dbms_application_info.set_action('SQL statement 43');
ALTER TABLE "ORACLE_TOOLS"."SCHEMA_OBJECT_FILTER_RESULTS" DROP PRIMARY KEY KEEP INDEX;

/* SQL statement 44 (ALTER;ORACLE_TOOLS;CONSTRAINT;SCHEMA_OBJECT_FILTER_RESULTS$CK$GENERATE_DDL;ORACLE_TOOLS;TABLE;SCHEMA_OBJECT_FILTER_RESULTS;;;;;2) */
call dbms_application_info.set_action('SQL statement 44');
ALTER TABLE "ORACLE_TOOLS"."SCHEMA_OBJECT_FILTER_RESULTS" DROP CONSTRAINT SCHEMA_OBJECT_FILTER_RESULTS$CK$GENERATE_DDL;

/* SQL statement 45 (ALTER;ORACLE_TOOLS;CONSTRAINT;SCHEMA_OBJECT_FILTERS$UK$1;ORACLE_TOOLS;TABLE;SCHEMA_OBJECT_FILTERS;;;;;2) */
call dbms_application_info.set_action('SQL statement 45');
ALTER TABLE "ORACLE_TOOLS"."SCHEMA_OBJECT_FILTERS" DROP UNIQUE ("HASH_BUCKET","HASH_BUCKET_NR") KEEP INDEX;

/* SQL statement 46 (ALTER;ORACLE_TOOLS;CONSTRAINT;SCHEMA_OBJECT_FILTERS$PK;ORACLE_TOOLS;TABLE;SCHEMA_OBJECT_FILTERS;;;;;2) */
call dbms_application_info.set_action('SQL statement 46');
ALTER TABLE "ORACLE_TOOLS"."SCHEMA_OBJECT_FILTERS" DROP PRIMARY KEY KEEP INDEX;

/* SQL statement 47 (ALTER;ORACLE_TOOLS;CONSTRAINT;SCHEMA_OBJECT_FILTERS$CK$ID;ORACLE_TOOLS;TABLE;SCHEMA_OBJECT_FILTERS;;;;;2) */
call dbms_application_info.set_action('SQL statement 47');
ALTER TABLE "ORACLE_TOOLS"."SCHEMA_OBJECT_FILTERS" DROP CONSTRAINT SCHEMA_OBJECT_FILTERS$CK$ID;

/* SQL statement 48 (ALTER;ORACLE_TOOLS;CONSTRAINT;SCHEMA_OBJECT_FILTERS$CK$HASH_BUCKET_NR;ORACLE_TOOLS;TABLE;SCHEMA_OBJECT_FILTERS;;;;;2) */
call dbms_application_info.set_action('SQL statement 48');
ALTER TABLE "ORACLE_TOOLS"."SCHEMA_OBJECT_FILTERS" DROP CONSTRAINT SCHEMA_OBJECT_FILTERS$CK$HASH_BUCKET_NR;

/* SQL statement 49 (ALTER;ORACLE_TOOLS;CONSTRAINT;SCHEMA_OBJECTS$PK;ORACLE_TOOLS;TABLE;SCHEMA_OBJECTS;;;;;2) */
call dbms_application_info.set_action('SQL statement 49');
ALTER TABLE "ORACLE_TOOLS"."SCHEMA_OBJECTS" DROP PRIMARY KEY KEEP INDEX;

/* SQL statement 50 (ALTER;ORACLE_TOOLS;CONSTRAINT;SCHEMA_OBJECTS$CK$OBJ;ORACLE_TOOLS;TABLE;SCHEMA_OBJECTS;;;;;2) */
call dbms_application_info.set_action('SQL statement 50');
ALTER TABLE "ORACLE_TOOLS"."SCHEMA_OBJECTS" DROP CONSTRAINT SCHEMA_OBJECTS$CK$OBJ;

/* SQL statement 51 (ALTER;ORACLE_TOOLS;CONSTRAINT;GENERATE_DDL_SESSION_SCHEMA_OBJECTS$UK$1;ORACLE_TOOLS;TABLE;GENERATE_DDL_SESSION_SCHEMA_OBJECTS;;;;;2) */
call dbms_application_info.set_action('SQL statement 51');
ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_SCHEMA_OBJECTS" DROP UNIQUE ("SESSION_ID","SCHEMA_OBJECT_ID") KEEP INDEX;

/* SQL statement 52 (ALTER;ORACLE_TOOLS;CONSTRAINT;GENERATE_DDL_SESSION_SCHEMA_OBJECTS$PK;ORACLE_TOOLS;TABLE;GENERATE_DDL_SESSION_SCHEMA_OBJECTS;;;;;2) */
call dbms_application_info.set_action('SQL statement 52');
ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_SCHEMA_OBJECTS" DROP PRIMARY KEY KEEP INDEX;

/* SQL statement 53 (ALTER;ORACLE_TOOLS;CONSTRAINT;GENERATE_DDL_SESSION_SCHEMA_OBJECTS$CK$SEQ;ORACLE_TOOLS;TABLE;GENERATE_DDL_SESSION_SCHEMA_OBJECTS;;;;;2) */
call dbms_application_info.set_action('SQL statement 53');
ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_SCHEMA_OBJECTS" DROP CONSTRAINT GENERATE_DDL_SESSION_SCHEMA_OBJECTS$CK$SEQ;

/* SQL statement 54 (ALTER;ORACLE_TOOLS;CONSTRAINT;GENERATE_DDL_SESSION_BATCHES$PK;ORACLE_TOOLS;TABLE;GENERATE_DDL_SESSION_BATCHES;;;;;2) */
call dbms_application_info.set_action('SQL statement 54');
ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSION_BATCHES" DROP PRIMARY KEY KEEP INDEX;

/* SQL statement 55 (ALTER;ORACLE_TOOLS;CONSTRAINT;GENERATE_DDL_SESSIONS$PK;ORACLE_TOOLS;TABLE;GENERATE_DDL_SESSIONS;;;;;2) */
call dbms_application_info.set_action('SQL statement 55');
ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_SESSIONS" DROP PRIMARY KEY KEEP INDEX;

/* SQL statement 56 (ALTER;ORACLE_TOOLS;CONSTRAINT;GENERATE_DDL_CONFIGURATIONS$UK$1;ORACLE_TOOLS;TABLE;GENERATE_DDL_CONFIGURATIONS;;;;;2) */
call dbms_application_info.set_action('SQL statement 56');
ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_CONFIGURATIONS" DROP UNIQUE ("TRANSFORM_PARAM_LIST","DB_VERSION","LAST_DDL_TIME_SCHEMA") KEEP INDEX;

/* SQL statement 57 (ALTER;ORACLE_TOOLS;CONSTRAINT;GENERATE_DDL_CONFIGURATIONS$PK;ORACLE_TOOLS;TABLE;GENERATE_DDL_CONFIGURATIONS;;;;;2) */
call dbms_application_info.set_action('SQL statement 57');
ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_CONFIGURATIONS" DROP PRIMARY KEY KEEP INDEX;

/* SQL statement 58 (ALTER;ORACLE_TOOLS;CONSTRAINT;GENERATE_DDL_CONFIGURATIONS$CK$1;ORACLE_TOOLS;TABLE;GENERATE_DDL_CONFIGURATIONS;;;;;2) */
call dbms_application_info.set_action('SQL statement 58');
ALTER TABLE "ORACLE_TOOLS"."GENERATE_DDL_CONFIGURATIONS" DROP CONSTRAINT GENERATE_DDL_CONFIGURATIONS$CK$1;

/* SQL statement 59 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_TEXT_TAB;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 59');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_TEXT_TAB" FROM "PUBLIC";

/* SQL statement 60 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_SCHEMA_OBJECT;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 60');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_SCHEMA_OBJECT" FROM "PUBLIC";

/* SQL statement 61 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_NAMED_OBJECT;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 61');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_NAMED_OBJECT" FROM "PUBLIC";

/* SQL statement 62 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_DDL;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 62');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_DDL" FROM "PUBLIC";

/* SQL statement 63 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_ARGUMENT_OBJECT_TAB;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 63');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_ARGUMENT_OBJECT_TAB" FROM "PUBLIC";

/* SQL statement 64 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_SCHEMA_OBJECT_TAB;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 64');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_SCHEMA_OBJECT_TAB" FROM "PUBLIC";

/* SQL statement 65 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_JAVA_SOURCE_OBJECT;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 65');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_JAVA_SOURCE_OBJECT" FROM "PUBLIC";

/* SQL statement 66 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_SEQUENCE_OBJECT;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 66');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_SEQUENCE_OBJECT" FROM "PUBLIC";

/* SQL statement 67 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_MATERIALIZED_VIEW_LOG_OBJECT;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 67');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_MATERIALIZED_VIEW_LOG_OBJECT" FROM "PUBLIC";

/* SQL statement 68 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_PROCEDURE_OBJECT;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 68');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_PROCEDURE_OBJECT" FROM "PUBLIC";

/* SQL statement 69 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_DDL_SEQUENCE;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 69');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_DDL_SEQUENCE" FROM "PUBLIC";

/* SQL statement 70 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_TYPE_BODY_OBJECT;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 70');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_TYPE_BODY_OBJECT" FROM "PUBLIC";

/* SQL statement 71 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_DEPENDENT_OR_GRANTED_OBJECT;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 71');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_DEPENDENT_OR_GRANTED_OBJECT" FROM "PUBLIC";

/* SQL statement 72 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_CLUSTER_OBJECT;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 72');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_CLUSTER_OBJECT" FROM "PUBLIC";

/* SQL statement 73 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_REFRESH_GROUP_OBJECT;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 73');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_REFRESH_GROUP_OBJECT" FROM "PUBLIC";

/* SQL statement 74 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_PACKAGE_SPEC_OBJECT;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 74');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_PACKAGE_SPEC_OBJECT" FROM "PUBLIC";

/* SQL statement 75 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_PACKAGE_BODY_OBJECT;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 75');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_PACKAGE_BODY_OBJECT" FROM "PUBLIC";

/* SQL statement 76 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_PROCOBJ_OBJECT;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 76');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_PROCOBJ_OBJECT" FROM "PUBLIC";

/* SQL statement 77 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_MATERIALIZED_VIEW_OBJECT;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 77');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_MATERIALIZED_VIEW_OBJECT" FROM "PUBLIC";

/* SQL statement 78 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_FUNCTION_OBJECT;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 78');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_FUNCTION_OBJECT" FROM "PUBLIC";

/* SQL statement 79 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_DDL_TAB;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 79');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_DDL_TAB" FROM "PUBLIC";

/* SQL statement 80 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_TYPE_SPEC_OBJECT;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 80');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_TYPE_SPEC_OBJECT" FROM "PUBLIC";

/* SQL statement 81 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_TABLE_OBJECT;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 81');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_TABLE_OBJECT" FROM "PUBLIC";

/* SQL statement 82 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_VIEW_OBJECT;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 82');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_VIEW_OBJECT" FROM "PUBLIC";

/* SQL statement 83 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_SCHEMA_OBJECT_FILTER;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 83');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_SCHEMA_OBJECT_FILTER" FROM "PUBLIC";

/* SQL statement 84 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_COMMENT_OBJECT;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 84');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_COMMENT_OBJECT" FROM "PUBLIC";

/* SQL statement 85 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_TRIGGER_OBJECT;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 85');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_TRIGGER_OBJECT" FROM "PUBLIC";

/* SQL statement 86 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_MEMBER_OBJECT;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 86');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_MEMBER_OBJECT" FROM "PUBLIC";

/* SQL statement 87 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_SCHEMA_DDL;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 87');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_SCHEMA_DDL" FROM "PUBLIC";

/* SQL statement 88 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_SYNONYM_OBJECT;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 88');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_SYNONYM_OBJECT" FROM "PUBLIC";

/* SQL statement 89 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_INDEX_OBJECT;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 89');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_INDEX_OBJECT" FROM "PUBLIC";

/* SQL statement 90 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_OBJECT_GRANT_OBJECT;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 90');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_OBJECT_GRANT_OBJECT" FROM "PUBLIC";

/* SQL statement 91 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_CONSTRAINT_OBJECT;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 91');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_CONSTRAINT_OBJECT" FROM "PUBLIC";

/* SQL statement 92 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_INDEX_DDL;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 92');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_INDEX_DDL" FROM "PUBLIC";

/* SQL statement 93 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_CONSTRAINT_DDL;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 93');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_CONSTRAINT_DDL" FROM "PUBLIC";

/* SQL statement 94 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_SEQUENCE_DDL;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 94');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_SEQUENCE_DDL" FROM "PUBLIC";

/* SQL statement 95 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_TYPE_ATTRIBUTE_OBJECT;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 95');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_TYPE_ATTRIBUTE_OBJECT" FROM "PUBLIC";

/* SQL statement 96 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_REF_CONSTRAINT_OBJECT;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 96');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_REF_CONSTRAINT_OBJECT" FROM "PUBLIC";

/* SQL statement 97 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_OBJECT_GRANT_DDL;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 97');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_OBJECT_GRANT_DDL" FROM "PUBLIC";

/* SQL statement 98 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_TABLE_DDL;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 98');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_TABLE_DDL" FROM "PUBLIC";

/* SQL statement 99 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_TYPE_METHOD_OBJECT;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 99');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_TYPE_METHOD_OBJECT" FROM "PUBLIC";

/* SQL statement 100 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_REFRESH_GROUP_DDL;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 100');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_REFRESH_GROUP_DDL" FROM "PUBLIC";

/* SQL statement 101 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_MATERIALIZED_VIEW_DDL;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 101');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_MATERIALIZED_VIEW_DDL" FROM "PUBLIC";

/* SQL statement 102 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_PROCOBJ_DDL;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 102');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_PROCOBJ_DDL" FROM "PUBLIC";

/* SQL statement 103 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_SCHEMA_DDL_TAB;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 103');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_SCHEMA_DDL_TAB" FROM "PUBLIC";

/* SQL statement 104 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_TRIGGER_DDL;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 104');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_TRIGGER_DDL" FROM "PUBLIC";

/* SQL statement 105 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_TYPE_METHOD_DDL;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 105');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_TYPE_METHOD_DDL" FROM "PUBLIC";

/* SQL statement 106 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_TYPE_SPEC_DDL;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 106');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_TYPE_SPEC_DDL" FROM "PUBLIC";

/* SQL statement 107 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_TYPE_ATTRIBUTE_DDL;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 107');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_TYPE_ATTRIBUTE_DDL" FROM "PUBLIC";

/* SQL statement 108 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_COMMENT_DDL;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 108');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_COMMENT_DDL" FROM "PUBLIC";

/* SQL statement 109 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_SYNONYM_DDL;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 109');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_SYNONYM_DDL" FROM "PUBLIC";

/* SQL statement 110 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_TABLE_COLUMN_DDL;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 110');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_TABLE_COLUMN_DDL" FROM "PUBLIC";

/* SQL statement 111 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_TABLE_COLUMN_OBJECT;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 111');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_TABLE_COLUMN_OBJECT" FROM "PUBLIC";

/* SQL statement 112 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;PACKAGE_SPEC;PKG_DDL_ERROR;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 112');
REVOKE EXECUTE ON "ORACLE_TOOLS"."PKG_DDL_ERROR" FROM "PUBLIC";

/* SQL statement 113 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;PACKAGE_SPEC;PKG_DDL_UTIL;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 113');
REVOKE EXECUTE ON "ORACLE_TOOLS"."PKG_DDL_UTIL" FROM "PUBLIC";

/* SQL statement 114 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;PACKAGE_SPEC;PKG_STR_UTIL;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 114');
REVOKE EXECUTE ON "ORACLE_TOOLS"."PKG_STR_UTIL" FROM "PUBLIC";

/* SQL statement 115 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;PACKAGE_SPEC;PKG_SCHEMA_OBJECT_FILTER;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 115');
REVOKE EXECUTE ON "ORACLE_TOOLS"."PKG_SCHEMA_OBJECT_FILTER" FROM "PUBLIC";

/* SQL statement 116 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;FUNCTION;F_GENERATE_DDL;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 116');
REVOKE EXECUTE ON "ORACLE_TOOLS"."F_GENERATE_DDL" FROM "PUBLIC";

/* SQL statement 117 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;PROCEDURE;P_GENERATE_DDL;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 117');
REVOKE EXECUTE ON "ORACLE_TOOLS"."P_GENERATE_DDL" FROM "PUBLIC";

/* SQL statement 118 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;VIEW;V_MY_SCHEMA_OBJECT_INFO;;PUBLIC;SELECT;NO;2) */
call dbms_application_info.set_action('SQL statement 118');
REVOKE SELECT ON "ORACLE_TOOLS"."V_MY_SCHEMA_OBJECT_INFO" FROM "PUBLIC";

/* SQL statement 119 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;VIEW;V_MY_INCLUDE_OBJECTS;;PUBLIC;SELECT;NO;2) */
call dbms_application_info.set_action('SQL statement 119');
REVOKE SELECT ON "ORACLE_TOOLS"."V_MY_INCLUDE_OBJECTS" FROM "PUBLIC";

/* SQL statement 120 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;VIEW;V_MY_SCHEMA_OBJECTS;;PUBLIC;SELECT;NO;2) */
call dbms_application_info.set_action('SQL statement 120');
REVOKE SELECT ON "ORACLE_TOOLS"."V_MY_SCHEMA_OBJECTS" FROM "PUBLIC";

/* SQL statement 121 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_DISPLAY_DDL_SQL_TAB;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 121');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_DISPLAY_DDL_SQL_TAB" FROM "PUBLIC";

/* SQL statement 122 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_DISPLAY_DDL_SQL_REC;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 122');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_DISPLAY_DDL_SQL_REC" FROM "PUBLIC";

/* SQL statement 123 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;SEQUENCE;SCHEMA_OBJECT_FILTERS$SEQ;;PUBLIC;SELECT;NO;2) */
call dbms_application_info.set_action('SQL statement 123');
REVOKE SELECT ON "ORACLE_TOOLS"."SCHEMA_OBJECT_FILTERS$SEQ" FROM "PUBLIC";

/* SQL statement 124 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;VIEW;V_ALL_SCHEMA_OBJECTS;;PUBLIC;SELECT;NO;2) */
call dbms_application_info.set_action('SQL statement 124');
REVOKE SELECT ON "ORACLE_TOOLS"."V_ALL_SCHEMA_OBJECTS" FROM "PUBLIC";

/* SQL statement 125 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;VIEW;V_MY_NAMED_SCHEMA_OBJECTS;;PUBLIC;SELECT;NO;2) */
call dbms_application_info.set_action('SQL statement 125');
REVOKE SELECT ON "ORACLE_TOOLS"."V_MY_NAMED_SCHEMA_OBJECTS" FROM "PUBLIC";

/* SQL statement 126 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;PACKAGE_SPEC;SCHEMA_OBJECTS_API;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 126');
REVOKE EXECUTE ON "ORACLE_TOOLS"."SCHEMA_OBJECTS_API" FROM "PUBLIC";

/* SQL statement 127 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;PACKAGE_SPEC;PKG_REPLICATE_UTIL;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 127');
REVOKE EXECUTE ON "ORACLE_TOOLS"."PKG_REPLICATE_UTIL" FROM "PUBLIC";

/* SQL statement 128 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;VIEW;V_DISPLAY_DDL_SQL;;PUBLIC;SELECT;NO;2) */
call dbms_application_info.set_action('SQL statement 128');
REVOKE SELECT ON "ORACLE_TOOLS"."V_DISPLAY_DDL_SQL" FROM "PUBLIC";

/* SQL statement 129 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;VIEW;V_MY_SCHEMA_OBJECTS_NO_DDL_YET;;PUBLIC;SELECT;NO;2) */
call dbms_application_info.set_action('SQL statement 129');
REVOKE SELECT ON "ORACLE_TOOLS"."V_MY_SCHEMA_OBJECTS_NO_DDL_YET" FROM "PUBLIC";

/* SQL statement 130 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;TYPE_SPEC;T_ARGUMENT_OBJECT;;PUBLIC;EXECUTE;NO;2) */
call dbms_application_info.set_action('SQL statement 130');
REVOKE EXECUTE ON "ORACLE_TOOLS"."T_ARGUMENT_OBJECT" FROM "PUBLIC";

/* SQL statement 131 (DROP;ORACLE_TOOLS;INDEX;SCHEMA_OBJECT_FILTER_RESULTS$FK$2;ORACLE_TOOLS;TABLE;SCHEMA_OBJECT_FILTER_RESULTS;;;;;2) */
call dbms_application_info.set_action('SQL statement 131');
DROP INDEX ORACLE_TOOLS.SCHEMA_OBJECT_FILTER_RESULTS$FK$2;

/* SQL statement 132 (DROP;ORACLE_TOOLS;INDEX;SCHEMA_OBJECTS$IDX$2;ORACLE_TOOLS;TABLE;SCHEMA_OBJECTS;;;;;2) */
call dbms_application_info.set_action('SQL statement 132');
DROP INDEX ORACLE_TOOLS.SCHEMA_OBJECTS$IDX$2;

/* SQL statement 133 (DROP;ORACLE_TOOLS;INDEX;SCHEMA_OBJECTS$IDX$1;ORACLE_TOOLS;TABLE;SCHEMA_OBJECTS;;;;;2) */
call dbms_application_info.set_action('SQL statement 133');
DROP INDEX ORACLE_TOOLS.SCHEMA_OBJECTS$IDX$1;

/* SQL statement 134 (DROP;ORACLE_TOOLS;INDEX;GENERATE_DDL_SESSION_SCHEMA_OBJECTS$FK$3;ORACLE_TOOLS;TABLE;GENERATE_DDL_SESSION_SCHEMA_OBJECTS;;;;;2) */
call dbms_application_info.set_action('SQL statement 134');
DROP INDEX ORACLE_TOOLS.GENERATE_DDL_SESSION_SCHEMA_OBJECTS$FK$3;

/* SQL statement 135 (DROP;ORACLE_TOOLS;INDEX;GENERATE_DDL_SESSION_SCHEMA_OBJECTS$FK$2;ORACLE_TOOLS;TABLE;GENERATE_DDL_SESSION_SCHEMA_OBJECTS;;;;;2) */
call dbms_application_info.set_action('SQL statement 135');
DROP INDEX ORACLE_TOOLS.GENERATE_DDL_SESSION_SCHEMA_OBJECTS$FK$2;

/* SQL statement 136 (DROP;ORACLE_TOOLS;INDEX;GENERATE_DDL_SESSION_SCHEMA_OBJECTS$FK$1;ORACLE_TOOLS;TABLE;GENERATE_DDL_SESSION_SCHEMA_OBJECTS;;;;;2) */
call dbms_application_info.set_action('SQL statement 136');
DROP INDEX ORACLE_TOOLS.GENERATE_DDL_SESSION_SCHEMA_OBJECTS$FK$1;

/* SQL statement 137 (DROP;ORACLE_TOOLS;INDEX;GENERATE_DDL_SESSIONS$FK$2;ORACLE_TOOLS;TABLE;GENERATE_DDL_SESSIONS;;;;;2) */
call dbms_application_info.set_action('SQL statement 137');
DROP INDEX ORACLE_TOOLS.GENERATE_DDL_SESSIONS$FK$2;

/* SQL statement 138 (DROP;ORACLE_TOOLS;INDEX;GENERATE_DDL_SESSIONS$FK$1;ORACLE_TOOLS;TABLE;GENERATE_DDL_SESSIONS;;;;;2) */
call dbms_application_info.set_action('SQL statement 138');
DROP INDEX ORACLE_TOOLS.GENERATE_DDL_SESSIONS$FK$1;

/* SQL statement 139 (DROP;ORACLE_TOOLS;TYPE_BODY;T_VIEW_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 139');
DROP TYPE BODY ORACLE_TOOLS.T_VIEW_OBJECT;

/* SQL statement 140 (DROP;ORACLE_TOOLS;TYPE_BODY;T_TYPE_SPEC_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 140');
DROP TYPE BODY ORACLE_TOOLS.T_TYPE_SPEC_OBJECT;

/* SQL statement 141 (DROP;ORACLE_TOOLS;TYPE_BODY;T_TYPE_SPEC_DDL;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 141');
DROP TYPE BODY ORACLE_TOOLS.T_TYPE_SPEC_DDL;

/* SQL statement 142 (DROP;ORACLE_TOOLS;TYPE_BODY;T_TYPE_METHOD_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 142');
DROP TYPE BODY ORACLE_TOOLS.T_TYPE_METHOD_OBJECT;

/* SQL statement 143 (DROP;ORACLE_TOOLS;TYPE_BODY;T_TYPE_METHOD_DDL;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 143');
DROP TYPE BODY ORACLE_TOOLS.T_TYPE_METHOD_DDL;

/* SQL statement 144 (DROP;ORACLE_TOOLS;TYPE_BODY;T_TYPE_BODY_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 144');
DROP TYPE BODY ORACLE_TOOLS.T_TYPE_BODY_OBJECT;

/* SQL statement 145 (DROP;ORACLE_TOOLS;TYPE_BODY;T_TYPE_ATTRIBUTE_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 145');
DROP TYPE BODY ORACLE_TOOLS.T_TYPE_ATTRIBUTE_OBJECT;

/* SQL statement 146 (DROP;ORACLE_TOOLS;TYPE_BODY;T_TYPE_ATTRIBUTE_DDL;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 146');
DROP TYPE BODY ORACLE_TOOLS.T_TYPE_ATTRIBUTE_DDL;

/* SQL statement 147 (DROP;ORACLE_TOOLS;TYPE_BODY;T_TRIGGER_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 147');
DROP TYPE BODY ORACLE_TOOLS.T_TRIGGER_OBJECT;

/* SQL statement 148 (DROP;ORACLE_TOOLS;TYPE_BODY;T_TRIGGER_DDL;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 148');
DROP TYPE BODY ORACLE_TOOLS.T_TRIGGER_DDL;

/* SQL statement 149 (DROP;ORACLE_TOOLS;TYPE_BODY;T_TABLE_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 149');
DROP TYPE BODY ORACLE_TOOLS.T_TABLE_OBJECT;

/* SQL statement 150 (DROP;ORACLE_TOOLS;TYPE_BODY;T_TABLE_DDL;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 150');
DROP TYPE BODY ORACLE_TOOLS.T_TABLE_DDL;

/* SQL statement 151 (DROP;ORACLE_TOOLS;TYPE_BODY;T_TABLE_COLUMN_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 151');
DROP TYPE BODY ORACLE_TOOLS.T_TABLE_COLUMN_OBJECT;

/* SQL statement 152 (DROP;ORACLE_TOOLS;TYPE_BODY;T_TABLE_COLUMN_DDL;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 152');
DROP TYPE BODY ORACLE_TOOLS.T_TABLE_COLUMN_DDL;

/* SQL statement 153 (DROP;ORACLE_TOOLS;TYPE_BODY;T_SYNONYM_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 153');
DROP TYPE BODY ORACLE_TOOLS.T_SYNONYM_OBJECT;

/* SQL statement 154 (DROP;ORACLE_TOOLS;TYPE_BODY;T_SYNONYM_DDL;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 154');
DROP TYPE BODY ORACLE_TOOLS.T_SYNONYM_DDL;

/* SQL statement 155 (DROP;ORACLE_TOOLS;TYPE_BODY;T_SEQUENCE_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 155');
DROP TYPE BODY ORACLE_TOOLS.T_SEQUENCE_OBJECT;

/* SQL statement 156 (DROP;ORACLE_TOOLS;TYPE_BODY;T_SEQUENCE_DDL;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 156');
DROP TYPE BODY ORACLE_TOOLS.T_SEQUENCE_DDL;

/* SQL statement 157 (DROP;ORACLE_TOOLS;TYPE_BODY;T_SCHEMA_OBJECT_FILTER;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 157');
DROP TYPE BODY ORACLE_TOOLS.T_SCHEMA_OBJECT_FILTER;

/* SQL statement 158 (DROP;ORACLE_TOOLS;TYPE_BODY;T_SCHEMA_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 158');
DROP TYPE BODY ORACLE_TOOLS.T_SCHEMA_OBJECT;

/* SQL statement 159 (DROP;ORACLE_TOOLS;TYPE_BODY;T_SCHEMA_DDL;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 159');
DROP TYPE BODY ORACLE_TOOLS.T_SCHEMA_DDL;

/* SQL statement 160 (DROP;ORACLE_TOOLS;TYPE_BODY;T_REF_CONSTRAINT_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 160');
DROP TYPE BODY ORACLE_TOOLS.T_REF_CONSTRAINT_OBJECT;

/* SQL statement 161 (DROP;ORACLE_TOOLS;TYPE_BODY;T_REFRESH_GROUP_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 161');
DROP TYPE BODY ORACLE_TOOLS.T_REFRESH_GROUP_OBJECT;

/* SQL statement 162 (DROP;ORACLE_TOOLS;TYPE_BODY;T_REFRESH_GROUP_DDL;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 162');
DROP TYPE BODY ORACLE_TOOLS.T_REFRESH_GROUP_DDL;

/* SQL statement 163 (DROP;ORACLE_TOOLS;TYPE_BODY;T_PROCOBJ_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 163');
DROP TYPE BODY ORACLE_TOOLS.T_PROCOBJ_OBJECT;

/* SQL statement 164 (DROP;ORACLE_TOOLS;TYPE_BODY;T_PROCOBJ_DDL;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 164');
DROP TYPE BODY ORACLE_TOOLS.T_PROCOBJ_DDL;

/* SQL statement 165 (DROP;ORACLE_TOOLS;TYPE_BODY;T_PROCEDURE_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 165');
DROP TYPE BODY ORACLE_TOOLS.T_PROCEDURE_OBJECT;

/* SQL statement 166 (DROP;ORACLE_TOOLS;TYPE_BODY;T_PACKAGE_SPEC_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 166');
DROP TYPE BODY ORACLE_TOOLS.T_PACKAGE_SPEC_OBJECT;

/* SQL statement 167 (DROP;ORACLE_TOOLS;TYPE_BODY;T_PACKAGE_BODY_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 167');
DROP TYPE BODY ORACLE_TOOLS.T_PACKAGE_BODY_OBJECT;

/* SQL statement 168 (DROP;ORACLE_TOOLS;TYPE_BODY;T_OBJECT_GRANT_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 168');
DROP TYPE BODY ORACLE_TOOLS.T_OBJECT_GRANT_OBJECT;

/* SQL statement 169 (DROP;ORACLE_TOOLS;TYPE_BODY;T_OBJECT_GRANT_DDL;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 169');
DROP TYPE BODY ORACLE_TOOLS.T_OBJECT_GRANT_DDL;

/* SQL statement 170 (DROP;ORACLE_TOOLS;TYPE_BODY;T_NAMED_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 170');
DROP TYPE BODY ORACLE_TOOLS.T_NAMED_OBJECT;

/* SQL statement 171 (DROP;ORACLE_TOOLS;TYPE_BODY;T_MEMBER_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 171');
DROP TYPE BODY ORACLE_TOOLS.T_MEMBER_OBJECT;

/* SQL statement 172 (DROP;ORACLE_TOOLS;TYPE_BODY;T_MATERIALIZED_VIEW_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 172');
DROP TYPE BODY ORACLE_TOOLS.T_MATERIALIZED_VIEW_OBJECT;

/* SQL statement 173 (DROP;ORACLE_TOOLS;TYPE_BODY;T_MATERIALIZED_VIEW_LOG_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 173');
DROP TYPE BODY ORACLE_TOOLS.T_MATERIALIZED_VIEW_LOG_OBJECT;

/* SQL statement 174 (DROP;ORACLE_TOOLS;TYPE_BODY;T_MATERIALIZED_VIEW_DDL;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 174');
DROP TYPE BODY ORACLE_TOOLS.T_MATERIALIZED_VIEW_DDL;

/* SQL statement 175 (DROP;ORACLE_TOOLS;TYPE_BODY;T_JAVA_SOURCE_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 175');
DROP TYPE BODY ORACLE_TOOLS.T_JAVA_SOURCE_OBJECT;

/* SQL statement 176 (DROP;ORACLE_TOOLS;TYPE_BODY;T_INDEX_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 176');
DROP TYPE BODY ORACLE_TOOLS.T_INDEX_OBJECT;

/* SQL statement 177 (DROP;ORACLE_TOOLS;TYPE_BODY;T_INDEX_DDL;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 177');
DROP TYPE BODY ORACLE_TOOLS.T_INDEX_DDL;

/* SQL statement 178 (DROP;ORACLE_TOOLS;TYPE_BODY;T_FUNCTION_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 178');
DROP TYPE BODY ORACLE_TOOLS.T_FUNCTION_OBJECT;

/* SQL statement 179 (DROP;ORACLE_TOOLS;TYPE_BODY;T_DEPENDENT_OR_GRANTED_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 179');
DROP TYPE BODY ORACLE_TOOLS.T_DEPENDENT_OR_GRANTED_OBJECT;

/* SQL statement 180 (DROP;ORACLE_TOOLS;TYPE_BODY;T_DDL_SEQUENCE;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 180');
DROP TYPE BODY ORACLE_TOOLS.T_DDL_SEQUENCE;

/* SQL statement 181 (DROP;ORACLE_TOOLS;TYPE_BODY;T_DDL;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 181');
DROP TYPE BODY ORACLE_TOOLS.T_DDL;

/* SQL statement 182 (DROP;ORACLE_TOOLS;TYPE_BODY;T_CONSTRAINT_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 182');
DROP TYPE BODY ORACLE_TOOLS.T_CONSTRAINT_OBJECT;

/* SQL statement 183 (DROP;ORACLE_TOOLS;TYPE_BODY;T_CONSTRAINT_DDL;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 183');
DROP TYPE BODY ORACLE_TOOLS.T_CONSTRAINT_DDL;

/* SQL statement 184 (DROP;ORACLE_TOOLS;TYPE_BODY;T_COMMENT_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 184');
DROP TYPE BODY ORACLE_TOOLS.T_COMMENT_OBJECT;

/* SQL statement 185 (DROP;ORACLE_TOOLS;TYPE_BODY;T_COMMENT_DDL;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 185');
DROP TYPE BODY ORACLE_TOOLS.T_COMMENT_DDL;

/* SQL statement 186 (DROP;ORACLE_TOOLS;TYPE_BODY;T_CLUSTER_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 186');
DROP TYPE BODY ORACLE_TOOLS.T_CLUSTER_OBJECT;

/* SQL statement 187 (DROP;ORACLE_TOOLS;TYPE_BODY;T_ARGUMENT_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 187');
DROP TYPE BODY ORACLE_TOOLS.T_ARGUMENT_OBJECT;

/* SQL statement 188 (DROP;ORACLE_TOOLS;PACKAGE_BODY;SCHEMA_OBJECTS_API;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 188');
DROP PACKAGE BODY ORACLE_TOOLS.SCHEMA_OBJECTS_API;

/* SQL statement 189 (DROP;ORACLE_TOOLS;PACKAGE_BODY;PKG_STR_UTIL;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 189');
DROP PACKAGE BODY ORACLE_TOOLS.PKG_STR_UTIL;

/* SQL statement 190 (DROP;ORACLE_TOOLS;PACKAGE_BODY;PKG_SCHEMA_OBJECT_FILTER;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 190');
DROP PACKAGE BODY ORACLE_TOOLS.PKG_SCHEMA_OBJECT_FILTER;

/* SQL statement 191 (DROP;ORACLE_TOOLS;PACKAGE_BODY;PKG_REPLICATE_UTIL;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 191');
DROP PACKAGE BODY ORACLE_TOOLS.PKG_REPLICATE_UTIL;

/* SQL statement 192 (DROP;ORACLE_TOOLS;PACKAGE_BODY;PKG_DDL_UTIL;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 192');
DROP PACKAGE BODY ORACLE_TOOLS.PKG_DDL_UTIL;

/* SQL statement 193 (DROP;ORACLE_TOOLS;PACKAGE_BODY;PKG_DDL_ERROR;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 193');
DROP PACKAGE BODY ORACLE_TOOLS.PKG_DDL_ERROR;

/* SQL statement 194 (DROP;ORACLE_TOOLS;PROCEDURE;P_GENERATE_DDL;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 194');
DROP PROCEDURE ORACLE_TOOLS.P_GENERATE_DDL;

/* SQL statement 195 (DROP;ORACLE_TOOLS;VIEW;V_MY_SCHEMA_OBJECT_INFO;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 195');
DROP VIEW ORACLE_TOOLS.V_MY_SCHEMA_OBJECT_INFO;

/* SQL statement 196 (DROP;ORACLE_TOOLS;VIEW;V_MY_SCHEMA_OBJECT_FILTER;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 196');
DROP VIEW ORACLE_TOOLS.V_MY_SCHEMA_OBJECT_FILTER;

/* SQL statement 197 (DROP;ORACLE_TOOLS;VIEW;V_MY_SCHEMA_OBJECTS_NO_DDL_YET;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 197');
DROP VIEW ORACLE_TOOLS.V_MY_SCHEMA_OBJECTS_NO_DDL_YET;

/* SQL statement 198 (DROP;ORACLE_TOOLS;VIEW;V_MY_SCHEMA_OBJECTS;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 198');
DROP VIEW ORACLE_TOOLS.V_MY_SCHEMA_OBJECTS;

/* SQL statement 199 (DROP;ORACLE_TOOLS;VIEW;V_MY_SCHEMA_DDLS;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 199');
DROP VIEW ORACLE_TOOLS.V_MY_SCHEMA_DDLS;

/* SQL statement 200 (DROP;ORACLE_TOOLS;VIEW;V_MY_OBJECT_GRANTS_DICT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 200');
DROP VIEW ORACLE_TOOLS.V_MY_OBJECT_GRANTS_DICT;

/* SQL statement 201 (DROP;ORACLE_TOOLS;VIEW;V_MY_NAMED_SCHEMA_OBJECTS;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 201');
DROP VIEW ORACLE_TOOLS.V_MY_NAMED_SCHEMA_OBJECTS;

/* SQL statement 202 (DROP;ORACLE_TOOLS;VIEW;V_MY_INCLUDE_OBJECTS;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 202');
DROP VIEW ORACLE_TOOLS.V_MY_INCLUDE_OBJECTS;

/* SQL statement 203 (DROP;ORACLE_TOOLS;VIEW;V_MY_GENERATE_DDL_SESSION_SCHEMA_DDL_BATCHES;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 203');
DROP VIEW ORACLE_TOOLS.V_MY_GENERATE_DDL_SESSION_SCHEMA_DDL_BATCHES;

/* SQL statement 204 (DROP;ORACLE_TOOLS;VIEW;V_MY_CONSTRAINTS_DICT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 204');
DROP VIEW ORACLE_TOOLS.V_MY_CONSTRAINTS_DICT;

/* SQL statement 205 (DROP;ORACLE_TOOLS;VIEW;V_MY_COMMENTS_DICT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 205');
DROP VIEW ORACLE_TOOLS.V_MY_COMMENTS_DICT;

/* SQL statement 206 (DROP;ORACLE_TOOLS;VIEW;V_DISPLAY_DDL_SQL;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 206');
DROP VIEW ORACLE_TOOLS.V_DISPLAY_DDL_SQL;

/* SQL statement 207 (DROP;ORACLE_TOOLS;VIEW;V_ALL_SCHEMA_OBJECTS;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 207');
DROP VIEW ORACLE_TOOLS.V_ALL_SCHEMA_OBJECTS;

/* SQL statement 208 (DROP;ORACLE_TOOLS;PACKAGE_SPEC;SCHEMA_OBJECTS_API;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 208');
DROP PACKAGE ORACLE_TOOLS.SCHEMA_OBJECTS_API;

/* SQL statement 209 (DROP;ORACLE_TOOLS;PACKAGE_SPEC;PKG_STR_UTIL;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 209');
DROP PACKAGE ORACLE_TOOLS.PKG_STR_UTIL;

/* SQL statement 210 (DROP;ORACLE_TOOLS;PACKAGE_SPEC;PKG_SCHEMA_OBJECT_FILTER;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 210');
DROP PACKAGE ORACLE_TOOLS.PKG_SCHEMA_OBJECT_FILTER;

/* SQL statement 211 (DROP;ORACLE_TOOLS;PACKAGE_SPEC;PKG_REPLICATE_UTIL;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 211');
DROP PACKAGE ORACLE_TOOLS.PKG_REPLICATE_UTIL;

/* SQL statement 212 (DROP;ORACLE_TOOLS;PACKAGE_SPEC;PKG_DDL_UTIL;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 212');
DROP PACKAGE ORACLE_TOOLS.PKG_DDL_UTIL;

/* SQL statement 213 (DROP;ORACLE_TOOLS;PACKAGE_SPEC;PKG_DDL_ERROR;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 213');
DROP PACKAGE ORACLE_TOOLS.PKG_DDL_ERROR;

/* SQL statement 214 (DROP;ORACLE_TOOLS;FUNCTION;F_GENERATE_DDL;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 214');
DROP FUNCTION ORACLE_TOOLS.F_GENERATE_DDL;

/* SQL statement 215 (DROP;ORACLE_TOOLS;TABLE;SCHEMA_OBJECT_FILTER_RESULTS;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 215');
DROP TABLE ORACLE_TOOLS.SCHEMA_OBJECT_FILTER_RESULTS PURGE;

/* SQL statement 216 (DROP;ORACLE_TOOLS;TABLE;SCHEMA_OBJECT_FILTERS;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 216');
DROP TABLE ORACLE_TOOLS.SCHEMA_OBJECT_FILTERS PURGE;

/* SQL statement 217 (DROP;ORACLE_TOOLS;TABLE;SCHEMA_OBJECTS;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 217');
DROP TABLE ORACLE_TOOLS.SCHEMA_OBJECTS PURGE;

/* SQL statement 218 (DROP;ORACLE_TOOLS;TABLE;GENERATE_DDL_SESSION_SCHEMA_OBJECTS;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 218');
DROP TABLE ORACLE_TOOLS.GENERATE_DDL_SESSION_SCHEMA_OBJECTS PURGE;

/* SQL statement 219 (DROP;ORACLE_TOOLS;TABLE;GENERATE_DDL_SESSION_BATCHES;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 219');
DROP TABLE ORACLE_TOOLS.GENERATE_DDL_SESSION_BATCHES PURGE;

/* SQL statement 220 (DROP;ORACLE_TOOLS;TABLE;GENERATE_DDL_SESSIONS;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 220');
DROP TABLE ORACLE_TOOLS.GENERATE_DDL_SESSIONS PURGE;

/* SQL statement 221 (DROP;ORACLE_TOOLS;TABLE;GENERATE_DDL_CONFIGURATIONS;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 221');
DROP TABLE ORACLE_TOOLS.GENERATE_DDL_CONFIGURATIONS PURGE;

/* SQL statement 222 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_VIEW_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 222');
DROP TYPE ORACLE_TOOLS.T_VIEW_OBJECT FORCE;

/* SQL statement 223 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_TYPE_SPEC_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 223');
DROP TYPE ORACLE_TOOLS.T_TYPE_SPEC_OBJECT FORCE;

/* SQL statement 224 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_TYPE_SPEC_DDL;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 224');
DROP TYPE ORACLE_TOOLS.T_TYPE_SPEC_DDL FORCE;

/* SQL statement 225 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_TYPE_METHOD_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 225');
DROP TYPE ORACLE_TOOLS.T_TYPE_METHOD_OBJECT FORCE;

/* SQL statement 226 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_TYPE_METHOD_DDL;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 226');
DROP TYPE ORACLE_TOOLS.T_TYPE_METHOD_DDL FORCE;

/* SQL statement 227 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_TYPE_BODY_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 227');
DROP TYPE ORACLE_TOOLS.T_TYPE_BODY_OBJECT FORCE;

/* SQL statement 228 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_TYPE_ATTRIBUTE_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 228');
DROP TYPE ORACLE_TOOLS.T_TYPE_ATTRIBUTE_OBJECT FORCE;

/* SQL statement 229 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_TYPE_ATTRIBUTE_DDL;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 229');
DROP TYPE ORACLE_TOOLS.T_TYPE_ATTRIBUTE_DDL FORCE;

/* SQL statement 230 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_TRIGGER_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 230');
DROP TYPE ORACLE_TOOLS.T_TRIGGER_OBJECT FORCE;

/* SQL statement 231 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_TRIGGER_DDL;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 231');
DROP TYPE ORACLE_TOOLS.T_TRIGGER_DDL FORCE;

/* SQL statement 232 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_TEXT_TAB;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 232');
DROP TYPE ORACLE_TOOLS.T_TEXT_TAB FORCE;

/* SQL statement 233 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_TABLE_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 233');
DROP TYPE ORACLE_TOOLS.T_TABLE_OBJECT FORCE;

/* SQL statement 234 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_TABLE_DDL;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 234');
DROP TYPE ORACLE_TOOLS.T_TABLE_DDL FORCE;

/* SQL statement 235 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_TABLE_COLUMN_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 235');
DROP TYPE ORACLE_TOOLS.T_TABLE_COLUMN_OBJECT FORCE;

/* SQL statement 236 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_TABLE_COLUMN_DDL;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 236');
DROP TYPE ORACLE_TOOLS.T_TABLE_COLUMN_DDL FORCE;

/* SQL statement 237 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_SYNONYM_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 237');
DROP TYPE ORACLE_TOOLS.T_SYNONYM_OBJECT FORCE;

/* SQL statement 238 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_SYNONYM_DDL;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 238');
DROP TYPE ORACLE_TOOLS.T_SYNONYM_DDL FORCE;

/* SQL statement 239 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_SEQUENCE_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 239');
DROP TYPE ORACLE_TOOLS.T_SEQUENCE_OBJECT FORCE;

/* SQL statement 240 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_SEQUENCE_DDL;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 240');
DROP TYPE ORACLE_TOOLS.T_SEQUENCE_DDL FORCE;

/* SQL statement 241 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_SCHEMA_OBJECT_TAB;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 241');
DROP TYPE ORACLE_TOOLS.T_SCHEMA_OBJECT_TAB FORCE;

/* SQL statement 242 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_SCHEMA_OBJECT_FILTER;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 242');
DROP TYPE ORACLE_TOOLS.T_SCHEMA_OBJECT_FILTER FORCE;

/* SQL statement 243 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_SCHEMA_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 243');
DROP TYPE ORACLE_TOOLS.T_SCHEMA_OBJECT FORCE;

/* SQL statement 244 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_SCHEMA_DDL_TAB;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 244');
DROP TYPE ORACLE_TOOLS.T_SCHEMA_DDL_TAB FORCE;

/* SQL statement 245 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_SCHEMA_DDL;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 245');
DROP TYPE ORACLE_TOOLS.T_SCHEMA_DDL FORCE;

/* SQL statement 246 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_REF_CONSTRAINT_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 246');
DROP TYPE ORACLE_TOOLS.T_REF_CONSTRAINT_OBJECT FORCE;

/* SQL statement 247 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_REFRESH_GROUP_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 247');
DROP TYPE ORACLE_TOOLS.T_REFRESH_GROUP_OBJECT FORCE;

/* SQL statement 248 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_REFRESH_GROUP_DDL;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 248');
DROP TYPE ORACLE_TOOLS.T_REFRESH_GROUP_DDL FORCE;

/* SQL statement 249 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_PROCOBJ_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 249');
DROP TYPE ORACLE_TOOLS.T_PROCOBJ_OBJECT FORCE;

/* SQL statement 250 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_PROCOBJ_DDL;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 250');
DROP TYPE ORACLE_TOOLS.T_PROCOBJ_DDL FORCE;

/* SQL statement 251 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_PROCEDURE_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 251');
DROP TYPE ORACLE_TOOLS.T_PROCEDURE_OBJECT FORCE;

/* SQL statement 252 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_PACKAGE_SPEC_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 252');
DROP TYPE ORACLE_TOOLS.T_PACKAGE_SPEC_OBJECT FORCE;

/* SQL statement 253 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_PACKAGE_BODY_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 253');
DROP TYPE ORACLE_TOOLS.T_PACKAGE_BODY_OBJECT FORCE;

/* SQL statement 254 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_OBJECT_GRANT_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 254');
DROP TYPE ORACLE_TOOLS.T_OBJECT_GRANT_OBJECT FORCE;

/* SQL statement 255 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_OBJECT_GRANT_DDL;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 255');
DROP TYPE ORACLE_TOOLS.T_OBJECT_GRANT_DDL FORCE;

/* SQL statement 256 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_NAMED_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 256');
DROP TYPE ORACLE_TOOLS.T_NAMED_OBJECT FORCE;

/* SQL statement 257 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_MEMBER_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 257');
DROP TYPE ORACLE_TOOLS.T_MEMBER_OBJECT FORCE;

/* SQL statement 258 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_MATERIALIZED_VIEW_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 258');
DROP TYPE ORACLE_TOOLS.T_MATERIALIZED_VIEW_OBJECT FORCE;

/* SQL statement 259 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_MATERIALIZED_VIEW_LOG_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 259');
DROP TYPE ORACLE_TOOLS.T_MATERIALIZED_VIEW_LOG_OBJECT FORCE;

/* SQL statement 260 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_MATERIALIZED_VIEW_DDL;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 260');
DROP TYPE ORACLE_TOOLS.T_MATERIALIZED_VIEW_DDL FORCE;

/* SQL statement 261 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_JAVA_SOURCE_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 261');
DROP TYPE ORACLE_TOOLS.T_JAVA_SOURCE_OBJECT FORCE;

/* SQL statement 262 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_INDEX_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 262');
DROP TYPE ORACLE_TOOLS.T_INDEX_OBJECT FORCE;

/* SQL statement 263 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_INDEX_DDL;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 263');
DROP TYPE ORACLE_TOOLS.T_INDEX_DDL FORCE;

/* SQL statement 264 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_FUNCTION_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 264');
DROP TYPE ORACLE_TOOLS.T_FUNCTION_OBJECT FORCE;

/* SQL statement 265 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_DISPLAY_DDL_SQL_TAB;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 265');
DROP TYPE ORACLE_TOOLS.T_DISPLAY_DDL_SQL_TAB FORCE;

/* SQL statement 266 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_DISPLAY_DDL_SQL_REC;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 266');
DROP TYPE ORACLE_TOOLS.T_DISPLAY_DDL_SQL_REC FORCE;

/* SQL statement 267 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_DEPENDENT_OR_GRANTED_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 267');
DROP TYPE ORACLE_TOOLS.T_DEPENDENT_OR_GRANTED_OBJECT FORCE;

/* SQL statement 268 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_DDL_TAB;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 268');
DROP TYPE ORACLE_TOOLS.T_DDL_TAB FORCE;

/* SQL statement 269 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_DDL_SEQUENCE;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 269');
DROP TYPE ORACLE_TOOLS.T_DDL_SEQUENCE FORCE;

/* SQL statement 270 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_DDL;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 270');
DROP TYPE ORACLE_TOOLS.T_DDL FORCE;

/* SQL statement 271 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_CONSTRAINT_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 271');
DROP TYPE ORACLE_TOOLS.T_CONSTRAINT_OBJECT FORCE;

/* SQL statement 272 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_CONSTRAINT_DDL;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 272');
DROP TYPE ORACLE_TOOLS.T_CONSTRAINT_DDL FORCE;

/* SQL statement 273 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_COMMENT_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 273');
DROP TYPE ORACLE_TOOLS.T_COMMENT_OBJECT FORCE;

/* SQL statement 274 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_COMMENT_DDL;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 274');
DROP TYPE ORACLE_TOOLS.T_COMMENT_DDL FORCE;

/* SQL statement 275 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_CLUSTER_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 275');
DROP TYPE ORACLE_TOOLS.T_CLUSTER_OBJECT FORCE;

/* SQL statement 276 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_ARGUMENT_OBJECT_TAB;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 276');
DROP TYPE ORACLE_TOOLS.T_ARGUMENT_OBJECT_TAB FORCE;

/* SQL statement 277 (DROP;ORACLE_TOOLS;TYPE_SPEC;T_ARGUMENT_OBJECT;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 277');
DROP TYPE ORACLE_TOOLS.T_ARGUMENT_OBJECT FORCE;

/* SQL statement 278 (DROP;ORACLE_TOOLS;SEQUENCE;SCHEMA_OBJECT_FILTERS$SEQ;;;;;;;;2) */
call dbms_application_info.set_action('SQL statement 278');
DROP SEQUENCE ORACLE_TOOLS.SCHEMA_OBJECT_FILTERS$SEQ;

