whenever oserror exit failure
whenever sqlerror exit failure
set define off sqlblanklines on
ALTER SESSION SET PLSQL_WARNINGS = 'ENABLE:ALL';

prompt @@R__09.PACKAGE_SPEC.CFG_INSTALL_PKG.sql
@@R__09.PACKAGE_SPEC.CFG_INSTALL_PKG.sql
prompt @@R__09.PACKAGE_SPEC.CFG_PKG.sql
@@R__09.PACKAGE_SPEC.CFG_PKG.sql
prompt @@R__14.PACKAGE_BODY.CFG_INSTALL_PKG.sql
@@R__14.PACKAGE_BODY.CFG_INSTALL_PKG.sql
prompt @@R__18.OBJECT_GRANT.CFG_INSTALL_PKG.sql
@@R__18.OBJECT_GRANT.CFG_INSTALL_PKG.sql
prompt @@R__18.OBJECT_GRANT.CFG_PKG.sql
@@R__18.OBJECT_GRANT.CFG_PKG.sql
