task :default => :serve

task :test do
  require 'html-proofer'
  sh "bundle exec jekyll build --drafts --config _config.yml,_config_development.yml"
  options = { :assume_extension => true }
  HTMLProofer.check_directory("./_site", options).run
end

task :serve do
  sh "bundle exec jekyll serve --incremental --config _config.yml,_config_development.yml"
end
